### ISSUE TITLE
Error "engine Not compatible" with node-red-node-email and NodeJs 20

### ISSUE THREAD

**Issue by softy2k** [node-red/node-red-nodes#1029]
I updated from **NodeJS 18** to **NodeJs 20**, and when I try to update **email node** from **2.0.0** to **2.0.1** I get the following error:

```
npm WARN config production Use `--omit=dev` instead.
npm ERROR! code EBADENGINE
npm ERROR! engine Unsupported engine
npm ERROR! engine Not compatible with your version of node/npm: @azure/msal-node@1.17.2
npm ERROR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.17.2
npm ERROR! notsup Required: {"node":"10 || 12 || 14 || 16 || 18"}
npm ERROR! notsup Current: {"npm":"10.1.0","node":"v20.6.1"}
```

**Comment by dceejay** [comment]
Can you post some more of the error - I have just installed on my pi with no issue
```
pi@pi3test:~/.node-red $ node -v
v20.6.1
pi@pi3test:~/.node-red $ npm i node-red-node-serialport

up to date, audited 152 packages in 7s

35 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
pi@pi3test:~/.node-red $ 
```

I'm not sure what `@azure/msal-node@1.17.2` is - but it's nothing to do with the email node !

**Comment by hardillb** [comment]
@dceejay the email node, not the serial node

**Comment by dceejay** [comment]
```
pi@pi3test:~/.node-red $ npm i node-red-node-email

added 1 package, and audited 152 packages in 10s

35 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by knolleary** [comment]
This is not an error relating to the email node - that just happens to be the module you are trying to upgrade when you run `npm`.

`npm` is checking the integrity of all modules and has found an issue with the module `@azure/msal-node`. Looking at that module on npm I can see if only recently added support for Node 20 in the last month under its 2.x version stream.

If you run `npm list @azure/msal-node` in your `.node-red` directory it will show you what module is pulling it in. You can then follow up with that module to see if they can update their dependency to the latest ` @azure/msal-node`.

**Comment by softy2k** [comment]
Some additional details, **at this moment**:

Windows Server 2022 , version : 21H2
npm: 10.1.0
NodeJS: 18.17.1 (switched back from 20.6.1)
node-red-node-email : 2.0.1

If I run` npm list @azure/msal-node` in .node-red directory :

```
C:\Users\Administrator\.node-red>npm list @azure/msal-node
node-red-project@0.0.1 C:\Users\Administrator\.node-red
`-- node-red-contrib-mssql-plus@0.10.2
  `-- mssql@9.1.1
    `-- tedious@15.1.3
      `-- @azure/identity@2.1.0
        `-- @azure/msal-node@1.17.2
```

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl ???

Will have to have a look at the dependency tree for mssql-plus -> mssql see if there is a path to azure/msal-node v2.

All I can suggest to the op for now is:
- downgrade to node v18
- raise an issue on node-red-contrib-mssql-plus

Closing this issue.

**Comment by softy2k** [comment]
I found something similar : https://github.com/bestlong/node-red-contrib-mssql-plus/issues/77

**Comment by Steve-Mcl** [comment]
@softy2k did you try the workaround? 

perhaps you would have time to try forking and updating dependencies as described in https://github.com/bestlong/node-red-contrib-mssql-plus/issues/77#issuecomment-1715966019 ? 

I have merge rights so will accept a PR for that node.

**Comment by Steve-Mcl** [comment]
@softy2k are you in a position to test on Node 20?

try `npm i node-red-contrib-mssql-plus@0.11.0-beta`

REF: https://github.com/bestlong/node-red-contrib-mssql-plus/issues/77#issuecomment-1717003223

**Comment by softy2k** [comment]
I can test, but in a few hours. The server is active, I can't stop it now.

**Comment by softy2k** [comment]
So:
1. I reinstalled **email node version 2.0.0**
2. I installed **NodeJS v20.6.1**
3. Just for testing, I tried to update the **email node** from NodeRed (**manage pallete**); I got the error with **EBADENGINE**
4. npm i node-red-contrib-mssql-plus@0.11.0-beta. It installed, but with some warnings:
```
C:\Users\Administrator\.node-red>npm i node-red-contrib-mssql-plus@0.11.0-beta
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: '@azure/msal-node@1.18.3',
npm WARN EBADENGINE required: { node: '10 || 12 || 14 || 16 || 18'},
npm WARN EBADENGINE current: { node: 'v20.6.1', npm: '10.1.0' }
npm WARN EBADENGINE }
```

5. restart NodeRed
6.  I tried to update the **email node** from NodeRed (**manage pallete**); I got error:
```
2023-09-13T19:06:59.802Z Install: node-red-node-email 2.0.1
2023-09-13T19:06:59.709Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node -red-node-email@2.0.1
2023-09-13T19:07:00.636Z [err] npm
2023-09-13T19:07:00.636Z [err] WARN
2023-09-13T19:07:00.636Z [err] config production Use `--omit=dev` instead.
2023-09-13T19:07:01.420Z [err] npm ERR!
2023-09-13T19:07:01.420Z [err] code EBADENGINE
2023-09-13T19:07:01.422Z [err] npm
2023-09-13T19:07:01.422Z [err] ERR! engine Unsupported engine
2023-09-13T19:07:01.422Z [err] npm ERR! engine
2023-09-13T19:07:01.422Z [err] Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-13T19:07:01.422Z [err] npm ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-13T19:07:01.422Z [err] npm ERR! notsup Required: {"node":"10 || 12 || 14 || 16 || 18"}
2023-09-13T19:07:01.422Z [err] npm ERR! notsup Current: {"npm":"10.1.0","node":"v20.6.1"}
2023-09-13T19:07:01.424Z [err]
2023-09-13T19:07:01.424Z [err] npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-09-13T19_07_00_581Z-debug-0.log
2023-09-13T19:07:01.439Z rc=1
```

**Comment by Steve-Mcl** [comment]
@softy2k thanks for the feedback. Can I please ask you to report your findings on the mssql-plus issue linked in earlier reply?  Doing so will alert myself and the repo owner so we can keep an eye on the dependencies and get this updated once all child dependencies have caught up.  

Plus, I thin it is fairly well established the email node thing was a trigger (not the cause)

Thanks.

**Comment by softy2k** [comment]
No problem **Steve-Mcl**, glad I can help the NodeRed community
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.1.0
2 info using node@v20.6.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 warn config production Use `--omit=dev` instead.
8 timing config:load:cli Completed in 3ms
9 timing config:load:env Completed in 0ms
10 timing config:load:file:C:\Users\Administrator\.node-red\.npmrc Completed in 1ms
11 timing config:load:project Completed in 1ms
12 timing config:load:file:C:\Users\Administrator\.npmrc Completed in 0ms
13 timing config:load:user Completed in 0ms
14 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 15ms
18 timing npm:load:configload Completed in 15ms
19 timing config:load:flatten Completed in 3ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install node-red-node-email@2.0.1
23 verbose argv "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix" "~" "--production" "--engine-strict" "node-red-node-email@2.0.1"
24 timing npm:load:setTitle Completed in 1ms
25 timing npm:load:display Completed in 1ms
26 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-09-14T04_59_55_978Z-
27 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-09-14T04_59_55_978Z-debug-0.log
28 timing npm:load:logFile Completed in 10ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 53ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 2 files
34 timing idealTree:init Completed in 297ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest node-red-node-email@2.0.1
38 silly logfile done cleaning log files
39 timing arborist:ctor Completed in 0ms
40 http fetch GET 200 https://registry.npmjs.org/node-red-node-email 1323ms (cache revalidated)
41 silly placeDep ROOT node-red-node-email@2.0.1 REPLACE for: node-red-project@0.0.1 want: 2.0.1
42 timing idealTree:#root Completed in 1341ms
43 timing idealTree:node_modules/node-red-node-email Completed in 0ms
44 timing idealTree:buildDeps Completed in 1343ms
45 timing idealTree:fixDepFlags Completed in 3ms
46 timing idealTree Completed in 1646ms
47 timing command:install Completed in 1656ms
48 verbose stack Error: Unsupported engine
48 verbose stack     at checkEngine (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\lib\index.js:14:25)
48 verbose stack     at #checkEngineAndPlatform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:213:11)
48 verbose stack     at Arborist.buildIdealTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:199:41)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
48 verbose stack     at async Install.exec (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:151:5)
48 verbose stack     at async module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js:61:5)
49 verbose pkgid @azure/msal-node@1.18.3
50 verbose cwd C:\Users\Administrator\.node-red
51 verbose Windows_NT 10.0.20348
52 verbose node v20.6.1
53 verbose npm  v10.1.0
54 error code EBADENGINE
55 error engine Unsupported engine
56 error engine Not compatible with your version of node/npm: @azure/msal-node@1.18.3
57 error notsup Not compatible with your version of node/npm: @azure/msal-node@1.18.3
57 error notsup Required: {"node":"10 || 12 || 14 || 16 || 18"}
57 error notsup Actual:   {"npm":"10.1.0","node":"v20.6.1"}
58 verbose exit 1
59 timing npm Completed in 2014ms
60 verbose unfinished npm timer reify 1694667596335
61 verbose unfinished npm timer reify:loadTrees 1694667596340
62 verbose code 1
```

**Comment by softy2k** [comment]
Same issue with **NodeJs 20.7.0**
OS: **Oracle Ubuntu**

```
2023-09-19T10:27:33.702Z Install : node-red-contrib-mssql-plus 0.11.0
2023-09-19T10:27:33.595Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-mssql-plus@0.11.0
2023-09-19T10:27:34.361Z [err] npm
2023-09-19T10:27:34.361Z [err]  
2023-09-19T10:27:34.361Z [err] WARN config production Use `--omit=dev` instead.
2023-09-19T10:27:40.970Z [err] npm
2023-09-19T10:27:40.971Z [err]  
2023-09-19T10:27:40.971Z [err] ERR!
2023-09-19T10:27:40.971Z [err]  
2023-09-19T10:27:40.971Z [err] code
2023-09-19T10:27:40.971Z [err]  EBADENGINE
2023-09-19T10:27:40.973Z [err] npm
2023-09-19T10:27:41.044Z [err]  
2023-09-19T10:27:41.044Z [err] ERR!
2023-09-19T10:27:41.044Z [err]  
2023-09-19T10:27:41.044Z [err] engine
2023-09-19T10:27:41.044Z [err]  Unsupported engine
2023-09-19T10:27:41.044Z [err] npm
2023-09-19T10:27:41.044Z [err]  ERR! engine
2023-09-19T10:27:41.044Z [err]  Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-19T10:27:41.045Z [err] npm 
2023-09-19T10:27:41.045Z [err] ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-19T10:27:41.045Z [err] npm ERR! notsup Required: {"node":"10 || 12 || 14 || 16 || 18"}
2023-09-19T10:27:41.045Z [err] npm ERR! notsup Actual:   {"npm":"10.1.0","node":"v20.7.0"}
2023-09-19T10:27:41.047Z [err] 
2023-09-19T10:27:41.047Z [err] npm ERR! A complete log of this run can be found in: /home/ubuntu/.npm/_logs/2023-09-19T10_27_34_159Z-debug-0.log
2023-09-19T10:27:41.055Z rc=1
```

**Comment by softy2k** [comment]
Same issue with **NodeJs 20.7.0**
OS: **Windows Server 2022 , version : 21H2**

```
2023-09-19T10:37:05.143Z Install : node-red-contrib-resend-last-msg 1.0.5
2023-09-19T10:37:05.026Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-resend-last-msg@1.0.5
2023-09-19T10:37:05.902Z [err] npm
2023-09-19T10:37:05.902Z [err]  WARN config production Use `--omit=dev` instead.
2023-09-19T10:37:08.008Z [err] npm
2023-09-19T10:37:08.008Z [err]  ERR! code EBADENGINE
2023-09-19T10:37:08.009Z [err] npm 
2023-09-19T10:37:08.009Z [err] ERR! engine Unsupported engine
2023-09-19T10:37:08.009Z [err] npm ERR! 
2023-09-19T10:37:08.009Z [err] engine Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-19T10:37:08.009Z [err] npm ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.18.3
2023-09-19T10:37:08.009Z [err] npm ERR! notsup Required: {"node":"10 || 12 || 14 || 16 || 18"}
2023-09-19T10:37:08.009Z [err] npm ERR! notsup Actual:   {"npm":"10.1.0","node":"v20.7.0"}
2023-09-19T10:37:08.011Z [err] 
2023-09-19T10:37:08.012Z [err] npm ERR!
2023-09-19T10:37:08.012Z [err]  A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-09-19T10_37_05_838Z-debug-0.log
2023-09-19T10:37:08.039Z rc=1
```
