### ISSUE TITLE
Error with node-red-node-discovery

### ISSUE THREAD

**Issue by natcl** [node-red/node-red-nodes#159]
I was fiddling with my router (disconnecting and reconnecting it) and I got this error that crashed node-red:

```
27 Dec 15:51:35 - Error: getaddrinfo -3008
    at errnoException (/Users/Nat/Source/nodered/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/Users/Nat/Source/nodered/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/Users/Nat/Source/nodered/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

It's not really a typical usage scenario but thought it might be good posting in case you want to catch that error...

Thanks !

**Comment by dceejay** [comment]
Thanks @natcl,
 If that is the full extent of the error logged then I'm guessing it's going to be an upstream issue that may be in a callback that we can't grab.. But... I will l have a look first.

**Comment by dceejay** [comment]
@natcl I have updated this node slightly to use the default resolver sequence... this may (depending on platform) then not use getAddrInfo - which may stop this happening... lots of mays in that but is about all be can do as when they get the error they do then throw it asynchronously rather than pass it all the way back up.

**Comment by natcl** [comment]
Thanks ! will let you know if I get another crash.
Happy new year !

**Comment by dceejay** [comment]
Any news ? If not can we close this and re-open if necessary ?

**Comment by natcl** [comment]
No crashes so far, we can close !
thanks !
