### ISSUE TITLE
Build errors for node-stringprep when trying to install node-red-node-xmpp

### ISSUE THREAD

**Issue by Shirk** [node-red/node-red-nodes#165]
When trying to run `npm install -g --unsafe-perms node-red-node-xmpp` I'm running into the following errors from npm:

```
make: Entering directory '/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build'
  CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:360:13: note: in expansion of macro ‘_NAN_ERROR’
     return  _NAN_ERROR(v8::Exception::Error, errmsg);
             ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(const char*)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:364:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:364:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(v8::Handle<v8::Value>)’:
../node_modules/nan/nan.h:369:5: error: ‘ThrowException’ is not a member of ‘v8’
     v8::ThrowException(error);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*, int)’:
../node_modules/nan/nan.h:376:53: error: ‘New’ is not a member of ‘v8::String’
     v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                     ^
../node_modules/nan/nan.h:378:14: error: ‘New’ is not a member of ‘v8::String’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
              ^
../node_modules/nan/nan.h:378:65: error: no matching function for call to ‘v8::Int32::New(const int&)’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                                                 ^
../node_modules/nan/nan.h:378:65: note: candidate is:
In file included from /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2499:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanTypeError(const char*)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:390:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::TypeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowTypeError(const char*)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:394:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:394:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanRangeError(const char*)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:398:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::RangeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowRangeError(const char*)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:402:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:402:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:421:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:137:71: note: in definition of macro ‘NAN_INLINE’
 # define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                       ^
../node_modules/nan/nan.h:421:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h:137:71: note: in definition of macro ‘NAN_INLINE’
 # define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                       ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:424:44: error: ‘callback’ was not declared in this scope
     return node::Buffer::New(data, length, callback, hint);
                                            ^
../node_modules/nan/nan.h:424:54: error: ‘hint’ was not declared in this scope
     return node::Buffer::New(data, length, callback, hint);
                                                      ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, uint32_t)’:
../node_modules/nan/nan.h:431:40: error: no matching function for call to ‘New(char*&, uint32_t&)’
     return node::Buffer::New(data, size);
                                        ^
../node_modules/nan/nan.h:431:40: note: candidates are:
In file included from ../node_modules/nan/nan.h:131:0,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note:   candidate expects 5 arguments, 2 provided
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note:   candidate expects 3 arguments, 2 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:435:34: error: no matching function for call to ‘New(uint32_t&)’
     return node::Buffer::New(size);
                                  ^
../node_modules/nan/nan.h:435:34: note: candidates are:
In file included from ../node_modules/nan/nan.h:131:0,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note:   candidate expects 2 arguments, 1 provided
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note:   candidate expects 3 arguments, 1 provided
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note:   candidate expects 5 arguments, 1 provided
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note:   candidate expects 3 arguments, 1 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:442:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(data, size);
            ^
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback()’:
../node_modules/nan/nan.h:712:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:712:49: note: candidate is:
In file included from /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2933:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2933:24: note:   candidate expects 1 argument, 0 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback(v8::Handle<v8::Function>&)’:
../node_modules/nan/nan.h:718:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:718:49: note: candidate is:
In file included from /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2933:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:2933:24: note:   candidate expects 1 argument, 0 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In destructor ‘NanCallback::~NanCallback()’:
../node_modules/nan/nan.h:725:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
     handle.Dispose();
            ^
../node_modules/nan/nan.h:726:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
            ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::SetFunction(v8::Handle<v8::Function>&)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:731:39: note: in expansion of macro ‘NanSymbol’
     NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
                                       ^
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Function> NanCallback::GetFunction()’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:735:46: note: in expansion of macro ‘NanSymbol’
     return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                              ^
../node_modules/nan/nan.h:736:25: error: expected primary-expression before ‘>’ token
         .As<v8::Function>();
                         ^
../node_modules/nan/nan.h:736:27: error: expected primary-expression before ‘)’ token
         .As<v8::Function>();
                           ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::Call(int, v8::Handle<v8::Value>*)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:744:13: note: in expansion of macro ‘NanSymbol’
         Get(NanSymbol("callback")).As<v8::Function>();
             ^
../node_modules/nan/nan.h:744:51: error: expected primary-expression before ‘>’ token
         Get(NanSymbol("callback")).As<v8::Function>();
                                                   ^
../node_modules/nan/nan.h:744:53: error: expected primary-expression before ‘)’ token
         Get(NanSymbol("callback")).As<v8::Function>();
                                                     ^
../node_modules/nan/nan.h:746:9: error: ‘GetCurrent’ is not a member of ‘v8::Context’
         v8::Context::GetCurrent()->Global()
         ^
../node_modules/nan/nan.h: In member function ‘void NanAsyncWorker::SavePersistent(const char*, v8::Local<v8::Object>&)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:793:17: note: in expansion of macro ‘NanSymbol’
     handle->Set(NanSymbol(key), obj);
                 ^
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Object> NanAsyncWorker::GetFromPersistent(const char*)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:800:24: note: in expansion of macro ‘NanSymbol’
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                        ^
../node_modules/nan/nan.h:800:53: error: expected primary-expression before ‘>’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                     ^
../node_modules/nan/nan.h:800:55: error: expected primary-expression before ‘)’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                       ^
../node_modules/nan/nan.h: In member function ‘virtual void NanAsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:822:30: error: ‘New’ is not a member of ‘v8::String’
         v8::Exception::Error(v8::String::New(errmsg))
                              ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../node_modules/nan/nan.h:990:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:991:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../node_modules/nan/nan.h:992:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:992:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../node-stringprep.cc: In static member function ‘static void StringPrep::Initialize(v8::Handle<v8::Object>)’:
../node-stringprep.cc:23:58: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
../node-stringprep.cc:23:58: note: candidate is:
In file included from /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:4349:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../node-stringprep.cc:28:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("StringPrep"), t->GetFunction());
                 ^
../node-stringprep.cc: In member function ‘v8::Handle<v8::Value> StringPrep::prepare(v8::String::Value&)’:
../node-stringprep.cc:139:34: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
             return v8::Undefined();
                                  ^
In file included from /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/.node-gyp/4.2.4/include/node/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../node-stringprep.cc:145:28: error: ‘New’ is not a member of ‘v8::String’
     Local<String> result = String::New(dest, destLen);
                            ^
../node-stringprep.cc: In function ‘void ToUnicode(const v8::FunctionCallbackInfo<v8::Value>&)’:
../node-stringprep.cc:230:28: error: ‘New’ is not a member of ‘v8::String’
     Local<String> result = String::New(dest, destLen);
                            ^
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In instantiation of ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:771:34:   required from here
../node_modules/nan/nan.h:415:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
     ^
node_stringprep.target.mk:86: recipe for target 'Release/obj.target/node_stringprep/node-stringprep.o' failed
make: *** [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
make: Leaving directory '/usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-red-node-xmpp/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```
At first I thought it was related to my system still running on Node v0.12 but I've since then upgraded to Node v4 and I'm still getting those errors (in fact the log from above was created by npm on Node v4).

**Comment by knolleary** [comment]
What version of npm are you using?

**Comment by Shirk** [comment]
I'm running npm 2.14.12 which was installed by the nodejs debian package.

**Comment by dceejay** [comment]
yes the node is pinned to use an old pre-req library...  we need to update that... will look at it. It may be simple version bump -- but may be more involved.

**Comment by dceejay** [comment]
Hi @shirk - I have updated the package and fixed some other small buglets around errors - pushed to npm as v0.1.2
