### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by YosemiteFall** [node-red/node-red-nodes#207]
Hello I've been running my mongo and node-red code and after a while this happened:

- TypeError: Cannot read property 'done' of null

    at /home/pi/.node-red/node_modules/mongodb/lib/mongodb/auth/mongodb_scram.js:165:17

    at /home/pi/.node-red/node_modules/mongodb/lib/mongodb/db.js:1169:16

    at /home/pi/.node-red/node_modules/mongodb/lib/mongodb/db.js:1878:9

    at Server.Base._callHandler (/home/pi/.node-red/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)

    at /home/pi/.node-red/node_modules/mongodb/lib/mongodb/connection/server.js:487:18

    at MongoReply.parseBody (/home/pi/.node-red/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

    at .<anonymous> (/home/pi/.node-red/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)

    at emitOne (events.js:96:13)

    at emit (events.js:188:7)

    at .<anonymous> (/home/pi/.node-red/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

how could i fix this?

thanks, will

**Comment by dceejay** [comment]
Hi,
what platform ? what OS ? which versions of node.js, npm and Node-RED ?
Which node is this ? If you install node-red-node-mongodb I would expect it to be in .node-red/node-modules/node-red-node-mongodb  - From the log above I'm seeing .node-red/node_modules/mongodb instead... so not sure if this is the Node-RED node...

**Comment by YosemiteFall** [comment]
hello,

I’m on a raspberry pi 3 raspbarian and I’m not sure the node version but its is the latest version.

**Comment by dceejay** [comment]
when you start Node-RED the versions are logged to the screen.

**Comment by YosemiteFall** [comment]
Could it be that I installed it to the wrong place?

From William Mawdsley

**Comment by knolleary** [comment]
@YosemiteFall right now it is not clear _what_ you have installed. The stack trace shows an issue inside the generic mongodb module. It doesn't tell us which mongo node-red node you have installed.

What node did you install?

Are you using the preinstalled node-red on Raspbian, or have you manually installed it? If you've manually installed it, what version of node.js are you using? (run "node -v" in a terminal to find out).
