### ISSUE TITLE
node-red-node-arduino installation problems

### ISSUE THREAD

**Issue by protolyser** [node-red/node-red-nodes#238]
Hi,
I have:
- Raspberry Pi 3, Linux 4.4.21-v7+ arm LE
- node v6.7.0
- npm v3.10.8
- node-RED v0.14.6

```
cd ~/.node-red
npm install node-red-node-arduino
```

gives me this:

```
pi@rasp:~ $ cd ~/.node-red
pi@rasp:~/.node-red $  npm install node-red-node-arduino
/home/pi/.node-red
└── node-red-node-arduino@0.0.9

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.
```
I also tried this:
```

pi@rasp:~/.node-red $ npm install -g node-red-node-arduino
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ node-red-node-arduino@0.0.9
  └─┬ firmata@0.13.0
    ├── browser-serialport@2.0.3
    ├── es6-shim@0.33.13
    └─┬ serialport@3.1.2
      ├── bindings@1.2.1
      ├─┬ commander@2.9.0
      │ └── graceful-readlink@1.0.1
      ├─┬ debug@2.2.0
      │ └── ms@0.7.1
      ├── es6-promise@3.3.1
      ├── nan@2.4.0
      ├─┬ node-pre-gyp@0.6.28
      │ ├─┬ mkdirp@0.5.1
      │ │ └── minimist@0.0.8
      │ ├─┬ nopt@3.0.6
      │ │ └── abbrev@1.0.7
      │ ├─┬ npmlog@2.0.3
      │ │ ├── ansi@0.3.1
      │ │ ├─┬ are-we-there-yet@1.1.2
      │ │ │ ├── delegates@1.0.0
      │ │ │ └─┬ readable-stream@2.1.2
      │ │ │   ├── core-util-is@1.0.2
      │ │ │   ├── inherits@2.0.1
      │ │ │   ├── isarray@1.0.0
      │ │ │   ├── process-nextick-args@1.0.7
      │ │ │   ├── string_decoder@0.10.31
      │ │ │   └── util-deprecate@1.0.2
      │ │ └─┬ gauge@1.2.7
      │ │   ├── has-unicode@2.0.0
      │ │   ├─┬ lodash.pad@4.4.0
      │ │   │ ├── lodash._baseslice@4.0.0
      │ │   │ ├── lodash._basetostring@4.12.0
      │ │   │ └── lodash.tostring@4.1.3
      │ │   ├─┬ lodash.padend@4.5.0
      │ │   │ ├── lodash._baseslice@4.0.0
      │ │   │ ├── lodash._basetostring@4.12.0
      │ │   │ └── lodash.tostring@4.1.3
      │ │   └─┬ lodash.padstart@4.5.0
      │ │     ├── lodash._baseslice@4.0.0
      │ │     ├── lodash._basetostring@4.12.0
      │ │     └── lodash.tostring@4.1.3
      │ ├─┬ rc@1.1.6
      │ │ ├── deep-extend@0.4.1
      │ │ ├── ini@1.3.4
      │ │ ├── minimist@1.2.0
      │ │ └── strip-json-comments@1.0.4
      │ ├─┬ request@2.72.0
      │ │ ├── aws-sign2@0.6.0
      │ │ ├── aws4@1.4.1
      │ │ ├─┬ bl@1.1.2
      │ │ │ └─┬ readable-stream@2.0.6
      │ │ │   ├── core-util-is@1.0.2
      │ │ │   ├── inherits@2.0.1
      │ │ │   ├── isarray@1.0.0
      │ │ │   ├── process-nextick-args@1.0.7
      │ │ │   ├── string_decoder@0.10.31
      │ │ │   └── util-deprecate@1.0.2
      │ │ ├── caseless@0.11.0
      │ │ ├─┬ combined-stream@1.0.5
      │ │ │ └── delayed-stream@1.0.0
      │ │ ├── extend@3.0.0
      │ │ ├── forever-agent@0.6.1
      │ │ ├─┬ form-data@1.0.0-rc4
      │ │ │ └── async@1.5.2
      │ │ ├─┬ har-validator@2.0.6
      │ │ │ ├─┬ chalk@1.1.3
      │ │ │ │ ├── ansi-styles@2.2.1
      │ │ │ │ ├── escape-string-regexp@1.0.5
      │ │ │ │ ├─┬ has-ansi@2.0.0
      │ │ │ │ │ └── ansi-regex@2.0.0
      │ │ │ │ ├─┬ strip-ansi@3.0.1
      │ │ │ │ │ └── ansi-regex@2.0.0
      │ │ │ │ └── supports-color@2.0.0
      │ │ │ ├─┬ is-my-json-valid@2.13.1
      │ │ │ │ ├── generate-function@2.0.0
      │ │ │ │ ├─┬ generate-object-property@1.2.0
      │ │ │ │ │ └── is-property@1.0.2
      │ │ │ │ ├── jsonpointer@2.0.0
      │ │ │ │ └── xtend@4.0.1
      │ │ │ └─┬ pinkie-promise@2.0.1
      │ │ │   └── pinkie@2.0.4
      │ │ ├─┬ hawk@3.1.3
      │ │ │ ├── boom@2.10.1
      │ │ │ ├── cryptiles@2.0.5
      │ │ │ ├── hoek@2.16.3
      │ │ │ └── sntp@1.0.9
      │ │ ├─┬ http-signature@1.1.1
      │ │ │ ├── assert-plus@0.2.0
      │ │ │ ├─┬ jsprim@1.2.2
      │ │ │ │ ├── extsprintf@1.0.2
      │ │ │ │ ├── json-schema@0.2.2
      │ │ │ │ └── verror@1.3.6
      │ │ │ └─┬ sshpk@1.8.3
      │ │ │   ├── asn1@0.2.3
      │ │ │   ├── assert-plus@1.0.0
      │ │ │   ├── dashdash@1.13.1
      │ │ │   ├── ecc-jsbn@0.1.1
      │ │ │   ├── getpass@0.1.6
      │ │ │   ├── jodid25519@1.0.2
      │ │ │   ├── jsbn@0.1.0
      │ │ │   └── tweetnacl@0.13.3
      │ │ ├── is-typedarray@1.0.0
      │ │ ├── isstream@0.1.2
      │ │ ├── json-stringify-safe@5.0.1
      │ │ ├─┬ mime-types@2.1.11
      │ │ │ └── mime-db@1.23.0
      │ │ ├── node-uuid@1.4.7
      │ │ ├── oauth-sign@0.8.2
      │ │ ├── qs@6.1.0
      │ │ ├── stringstream@0.0.5
      │ │ ├── tough-cookie@2.2.2
      │ │ └── tunnel-agent@0.4.3
      │ ├─┬ rimraf@2.5.2
      │ │ └─┬ glob@7.0.3
      │ │   ├─┬ inflight@1.0.4
      │ │   │ └── wrappy@1.0.1
      │ │   ├── inherits@2.0.1
      │ │   ├─┬ minimatch@3.0.0
      │ │   │ └─┬ brace-expansion@1.1.4
      │ │   │   ├── balanced-match@0.4.1
      │ │   │   └── concat-map@0.0.1
      │ │   ├─┬ once@1.3.3
      │ │   │ └── wrappy@1.0.1
      │ │   └── path-is-absolute@1.0.0
      │ ├── semver@5.1.0
      │ ├─┬ tar@2.2.1
      │ │ ├── block-stream@0.0.9
      │ │ ├─┬ fstream@1.0.9
      │ │ │ └── graceful-fs@4.1.4
      │ │ └── inherits@2.0.1
      │ └─┬ tar-pack@3.1.3
      │   ├─┬ fstream@1.0.9
      │   │ ├── graceful-fs@4.1.4
      │   │ └── inherits@2.0.1
      │   ├─┬ fstream-ignore@1.0.4
      │   │ ├── inherits@2.0.1
      │   │ └─┬ minimatch@3.0.0
      │   │   └─┬ brace-expansion@1.1.4
      │   │     ├── balanced-match@0.4.1
      │   │     └── concat-map@0.0.1
      │   ├─┬ once@1.3.3
      │   │ └── wrappy@1.0.1
      │   ├─┬ readable-stream@2.0.6
      │   │ ├── core-util-is@1.0.2
      │   │ ├── inherits@2.0.1
      │   │ ├── isarray@1.0.0
      │   │ ├── process-nextick-args@1.0.7
      │   │ ├── string_decoder@0.10.31
      │   │ └── util-deprecate@1.0.2
      │   └── uid-number@0.0.6
      └─┬ object.assign@4.0.4
        ├─┬ define-properties@1.1.2
        │ └── foreach@2.0.5
        ├── function-bind@1.1.0
        └── object-keys@1.0.11

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-red-node-arduino"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
eld.
npm WARN .node-red No README data
npm WARN .node-red No license field.
```

Then I tried this:

```
pi@rasp:~/.node-red $ npm install -g node-red-node-arduino
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ node-red-node-arduino@0.0.9
  └─┬ firmata@0.13.0
    ├── browser-serialport@2.0.3
    ├── es6-shim@0.33.13
    └─┬ serialport@3.1.2
      ├── bindings@1.2.1
      ├─┬ commander@2.9.0
      │ └── graceful-readlink@1.0.1
      ├─┬ debug@2.2.0
      │ └── ms@0.7.1
      ├── es6-promise@3.3.1
      ├── nan@2.4.0
      ├─┬ node-pre-gyp@0.6.28
      │ ├─┬ mkdirp@0.5.1
      │ │ └── minimist@0.0.8
      │ ├─┬ nopt@3.0.6
      │ │ └── abbrev@1.0.7
      │ ├─┬ npmlog@2.0.3
      │ │ ├── ansi@0.3.1
      │ │ ├─┬ are-we-there-yet@1.1.2
      │ │ │ ├── delegates@1.0.0
      │ │ │ └─┬ readable-stream@2.1.2
      │ │ │   ├── core-util-is@1.0.2
      │ │ │   ├── inherits@2.0.1
      │ │ │   ├── isarray@1.0.0
      │ │ │   ├── process-nextick-args@1.0.7
      │ │ │   ├── string_decoder@0.10.31
      │ │ │   └── util-deprecate@1.0.2
      │ │ └─┬ gauge@1.2.7
      │ │   ├── has-unicode@2.0.0
      │ │   ├─┬ lodash.pad@4.4.0
      │ │   │ ├── lodash._baseslice@4.0.0
      │ │   │ ├── lodash._basetostring@4.12.0
      │ │   │ └── lodash.tostring@4.1.3
      │ │   ├─┬ lodash.padend@4.5.0
      │ │   │ ├── lodash._baseslice@4.0.0
      │ │   │ ├── lodash._basetostring@4.12.0
      │ │   │ └── lodash.tostring@4.1.3
      │ │   └─┬ lodash.padstart@4.5.0
      │ │     ├── lodash._baseslice@4.0.0
      │ │     ├── lodash._basetostring@4.12.0
      │ │     └── lodash.tostring@4.1.3
      │ ├─┬ rc@1.1.6
      │ │ ├── deep-extend@0.4.1
      │ │ ├── ini@1.3.4
      │ │ ├── minimist@1.2.0
      │ │ └── strip-json-comments@1.0.4
      │ ├─┬ request@2.72.0
      │ │ ├── aws-sign2@0.6.0
      │ │ ├── aws4@1.4.1
      │ │ ├─┬ bl@1.1.2
      │ │ │ └─┬ readable-stream@2.0.6
      │ │ │   ├── core-util-is@1.0.2
      │ │ │   ├── inherits@2.0.1
      │ │ │   ├── isarray@1.0.0
      │ │ │   ├── process-nextick-args@1.0.7
      │ │ │   ├── string_decoder@0.10.31
      │ │ │   └── util-deprecate@1.0.2
      │ │ ├── caseless@0.11.0
      │ │ ├─┬ combined-stream@1.0.5
      │ │ │ └── delayed-stream@1.0.0
      │ │ ├── extend@3.0.0
      │ │ ├── forever-agent@0.6.1
      │ │ ├─┬ form-data@1.0.0-rc4
      │ │ │ └── async@1.5.2
      │ │ ├─┬ har-validator@2.0.6
      │ │ │ ├─┬ chalk@1.1.3
      │ │ │ │ ├── ansi-styles@2.2.1
      │ │ │ │ ├── escape-string-regexp@1.0.5
      │ │ │ │ ├─┬ has-ansi@2.0.0
      │ │ │ │ │ └── ansi-regex@2.0.0
      │ │ │ │ ├─┬ strip-ansi@3.0.1
      │ │ │ │ │ └── ansi-regex@2.0.0
      │ │ │ │ └── supports-color@2.0.0
      │ │ │ ├─┬ is-my-json-valid@2.13.1
      │ │ │ │ ├── generate-function@2.0.0
      │ │ │ │ ├─┬ generate-object-property@1.2.0
      │ │ │ │ │ └── is-property@1.0.2
      │ │ │ │ ├── jsonpointer@2.0.0
      │ │ │ │ └── xtend@4.0.1
      │ │ │ └─┬ pinkie-promise@2.0.1
      │ │ │   └── pinkie@2.0.4
      │ │ ├─┬ hawk@3.1.3
      │ │ │ ├── boom@2.10.1
      │ │ │ ├── cryptiles@2.0.5
      │ │ │ ├── hoek@2.16.3
      │ │ │ └── sntp@1.0.9
      │ │ ├─┬ http-signature@1.1.1
      │ │ │ ├── assert-plus@0.2.0
      │ │ │ ├─┬ jsprim@1.2.2
      │ │ │ │ ├── extsprintf@1.0.2
      │ │ │ │ ├── json-schema@0.2.2
      │ │ │ │ └── verror@1.3.6
      │ │ │ └─┬ sshpk@1.8.3
      │ │ │   ├── asn1@0.2.3
      │ │ │   ├── assert-plus@1.0.0
      │ │ │   ├── dashdash@1.13.1
      │ │ │   ├── ecc-jsbn@0.1.1
      │ │ │   ├── getpass@0.1.6
      │ │ │   ├── jodid25519@1.0.2
      │ │ │   ├── jsbn@0.1.0
      │ │ │   └── tweetnacl@0.13.3
      │ │ ├── is-typedarray@1.0.0
      │ │ ├── isstream@0.1.2
      │ │ ├── json-stringify-safe@5.0.1
      │ │ ├─┬ mime-types@2.1.11
      │ │ │ └── mime-db@1.23.0
      │ │ ├── node-uuid@1.4.7
      │ │ ├── oauth-sign@0.8.2
      │ │ ├── qs@6.1.0
      │ │ ├── stringstream@0.0.5
      │ │ ├── tough-cookie@2.2.2
      │ │ └── tunnel-agent@0.4.3
      │ ├─┬ rimraf@2.5.2
      │ │ └─┬ glob@7.0.3
      │ │   ├─┬ inflight@1.0.4
      │ │   │ └── wrappy@1.0.1
      │ │   ├── inherits@2.0.1
      │ │   ├─┬ minimatch@3.0.0
      │ │   │ └─┬ brace-expansion@1.1.4
      │ │   │   ├── balanced-match@0.4.1
      │ │   │   └── concat-map@0.0.1
      │ │   ├─┬ once@1.3.3
      │ │   │ └── wrappy@1.0.1
      │ │   └── path-is-absolute@1.0.0
      │ ├── semver@5.1.0
      │ ├─┬ tar@2.2.1
      │ │ ├── block-stream@0.0.9
      │ │ ├─┬ fstream@1.0.9
      │ │ │ └── graceful-fs@4.1.4
      │ │ └── inherits@2.0.1
      │ └─┬ tar-pack@3.1.3
      │   ├─┬ fstream@1.0.9
      │   │ ├── graceful-fs@4.1.4
      │   │ └── inherits@2.0.1
      │   ├─┬ fstream-ignore@1.0.4
      │   │ ├── inherits@2.0.1
      │   │ └─┬ minimatch@3.0.0
      │   │   └─┬ brace-expansion@1.1.4
      │   │     ├── balanced-match@0.4.1
      │   │     └── concat-map@0.0.1
      │   ├─┬ once@1.3.3
      │   │ └── wrappy@1.0.1
      │   ├─┬ readable-stream@2.0.6
      │   │ ├── core-util-is@1.0.2
      │   │ ├── inherits@2.0.1
      │   │ ├── isarray@1.0.0
      │   │ ├── process-nextick-args@1.0.7
      │   │ ├── string_decoder@0.10.31
      │   │ └── util-deprecate@1.0.2
      │   └── uid-number@0.0.6
      └─┬ object.assign@4.0.4
        ├─┬ define-properties@1.1.2
        │ └── foreach@2.0.5
        ├── function-bind@1.1.0
        └── object-keys@1.0.11

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-red-node-arduino"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
pi@rasp~/.node-red $ ^C
pi@rasp:~/.node-red $ sudo npm install -g node-red-node-arduino

> serialport@3.1.2 install /usr/lib/node_modules/node-red-node-arduino/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@3.1.2 and node@6.7.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/6.7.0/include/node/common.gypi', needed by 'Makefile'.  Schluss.
make: Leaving directory '/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.21-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/lib/node_modules/node-red-node-arduino/node_modules/serialport
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.21-v7+
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-red-node-arduino/node_modules/serialport
node-pre-gyp ERR! node -v v6.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/lib/node_modules/node-red-node-arduino/node_modules/serialport/build/Release' (1)
/usr/lib
└── (empty)

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-red-node-arduino"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! serialport@3.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@3.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! code 1

```

And when I start node-red this happens:
```
pi@rasp:~/.node-red $ sudo node-red


Welcome to Node-RED
===================

10 Oct 15:09:17 - [info] Node-RED version: v0.14.6
10 Oct 15:09:17 - [info] Node.js  version: v6.7.0
10 Oct 15:09:17 - [info] Linux 4.4.21-v7+ arm LE
10 Oct 15:09:17 - [info] Loading palette nodes
10 Oct 15:09:20 - [info] Dashboard started at /ui
10 Oct 15:09:21 - [info] Settings file  : /root/.node-red/settings.js
10 Oct 15:09:21 - [info] User directory : /root/.node-red
10 Oct 15:09:21 - [info] Flows file     : /root/.node-red/flows_rasp.json
10 Oct 15:09:21 - [info] Server now running at http://127.0.0.1:1880/
10 Oct 15:09:21 - [info] Waiting for missing types to be registered:
10 Oct 15:09:21 - [info]  - arduino-board (provided by npm module node-red-node-arduino)
10 Oct 15:09:21 - [info] To install any of these missing modules, run:
10 Oct 15:09:21 - [info]   npm install <module name>
10 Oct 15:09:21 - [info] in the directory:
10 Oct 15:09:21 - [info]   /root/.node-red
```

What can I do?
I'm not sure about the whole "sudo or not sudo, -g oder no -g" thing. I use node-red-contrib-rcswitch2 which uses wiredpi and needs sudo I think.

**Comment by knolleary** [comment]
The first set of messages:

```
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.
```

are only warnings, not errors. They are because you are running npm 3.x and it expects you to have a valid `package.json` file in whichever directory you are running npm in. It is unrelated to any specific npm module you are installing. You can ignore those warnings.


When you run `npm` without the `-g` option, it tries to install in the directory you are running the command in.

When you run it with the `-g` option, it tries to install it as a global dependency. This typically requires writing into directories that normal users don't have access to, and must be done as the 'root' user. This is done using the `sudo` command:

    sudo npm install -g node-red-node-arduino


Please note, for general questions like this, please use the mailing list.

**Comment by protolyser** [comment]
with sudo npm install -g node-red-node-arduino
I get the errors above.
Noob question: Where can I find the mailinglist?

**Comment by knolleary** [comment]
The mailing list is linked at the bottom of http://nodered.org

Ah sorry, I didn't spot you had tried sudo amongst that output. You need the `--unsafe-perm` option as well then:

    sudo npm install -g --unsafe-perm node-red-node-arduino

**Comment by protolyser** [comment]
ok thanks that does the installation.
however I still get that error when starting node-red
```
pi@rasp:~/.node-red $ sudo node-red


Welcome to Node-RED
===================

10 Oct 15:09:17 - [info] Node-RED version: v0.14.6
10 Oct 15:09:17 - [info] Node.js  version: v6.7.0
10 Oct 15:09:17 - [info] Linux 4.4.21-v7+ arm LE
10 Oct 15:09:17 - [info] Loading palette nodes
10 Oct 15:09:20 - [info] Dashboard started at /ui
10 Oct 15:09:21 - [info] Settings file  : /root/.node-red/settings.js
10 Oct 15:09:21 - [info] User directory : /root/.node-red
10 Oct 15:09:21 - [info] Flows file     : /root/.node-red/flows_rasp.json
10 Oct 15:09:21 - [info] Server now running at http://127.0.0.1:1880/
10 Oct 15:09:21 - [info] Waiting for missing types to be registered:
10 Oct 15:09:21 - [info]  - arduino-board (provided by npm module node-red-node-arduino)
10 Oct 15:09:21 - [info] To install any of these missing modules, run:
10 Oct 15:09:21 - [info]   npm install <module name>
10 Oct 15:09:21 - [info] in the directory:
10 Oct 15:09:21 - [info]   /root/.node-red
```

**Comment by dceejay** [comment]
this is one of those - falling between two stools - type issues.
In order to support node 6 then we would need to move the arduino node on to use latest firmata version - which in turn uses the latest serialport version (v4)  - which in turn drops support for v0.10.  

So until we no longer want to support v0.10 (and all those Pi users) then we don't really want to move this on - so the recommendation is to stick with node.js 4.x rather than 6. (for now)

**Comment by protolyser** [comment]
oh I see, how can I downgrade to 4.x without destroying everything?

**Comment by dceejay** [comment]
depends how you installed nodejs... ideally apt-get remove nodejs - then start over as per the docs... but yes it would be wise to backup your ~/.node-red directory just in case.
If you were on a recent Pi install you may have had a script on there  /usr/bin/update-nodejs-and-nodered which may work - but I have never tried it in this situation directly.

**Comment by protolyser** [comment]
I did a complete reinstall of my Raspberry PI now and installed
`node v4.6.0`
`npm 3.10.8`

Now I still get this error when I do
`sudo node-red`
`[arduino] Error: Cannot find module 'firmata/node_modules/serialport'`

**Comment by protolyser** [comment]
`sudo npm install -g npm@2.x `
and then again
`sudo npm install -g --unsafe-perm node-red-node-arduino`

..and it works, seems like there are problems with npm 3.x

**Comment by dceejay** [comment]
thanks for digging around this... so it's npm 3 rather than node 6 (probably)... but yeah... going to be a painful couple of months until we can drop node v0.10.
