### ISSUE TITLE
Email In Node Crashed Node-RED

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red-nodes#259]
```
10 Dec 09:50:09 - [info] [e-mail in:a] Checking IMAP for new messages                                                               
10 Dec 09:50:09 - [red] Uncaught Exception:                                                                                         
10 Dec 09:50:09 - TypeError: Cannot read property 'type' of undefined                                                               
    at Connection._resUntagged (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Connection.js:
1260:51)                                                                                                                            
    at Parser.<anonymous> (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Connection.js:190:1
0)                                                                                                                                  
    at emitOne (events.js:96:13)                                                                                                    
    at Parser.emit (events.js:188:7)                                                                                                
    at Parser._resUntagged (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:271:10) 
    at Parser._parse (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:137:16)       
    at Parser._tryread (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:82:15)      
    at TLSSocket.Parser._cbReadable (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js
:53:12)                                                                                                                             
    at emitNone (events.js:86:13)                                                                                                   
    at TLSSocket.emit (events.js:185:7)                                                                                             
    at emitReadable_ (_stream_readable.js:432:10)                                                                                   
    at emitReadable (_stream_readable.js:426:7)                                                                                     
    at readableAddChunk (_stream_readable.js:187:13)                                                                                
    at TLSSocket.Readable.push (_stream_readable.js:134:10)                                                                         
    at TLSWrap.onread (net.js:548:20)                                                                                               
    at Socket.ondata (_stream_wrap.js:58:20)                                                                                        
    at emitOne (events.js:96:13)                                                                                                    
    at Socket.emit (events.js:188:7)                                                                                                
    at readableAddChunk (_stream_readable.js:176:18)                                                                                
    at Socket.Readable.push (_stream_readable.js:134:10)                                                                            
    at TCP.onread (net.js:548:20)       
```                                                                                            

Running on Windows 10 (Windows_NT 10.0.14393 x64 LE), Node.js v6.9.1, latest Node-RED v0.15.2

Restarting causes another error:

```
10 Dec 14:03:02 - [info] [e-mail in:a] Checking IMAP for new messages                                                               
10 Dec 14:03:03 - [red] Uncaught Exception:                                                                                         
10 Dec 14:03:03 - TypeError: Cannot set property 'name' of undefined                                                                
    at Connection.<anonymous> (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Connection.js:4
26:22)                                                                                                                              
    at Connection._resTagged (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Connection.js:15
30:22)                                                                                                                              
    at Parser.<anonymous> (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Connection.js:193:1
0)                                                                                                                                  
    at emitOne (events.js:96:13)                                                                                                    
    at Parser.emit (events.js:188:7)                                                                                                
    at Parser._resTagged (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:175:10)   
    at Parser._parse (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:139:16)       
    at Parser._tryread (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js:82:15)      
    at TLSSocket.Parser._cbReadable (C:\Users\julia\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\node_modules\imap\lib\Parser.js
:53:12)                                                                                                                             
    at emitNone (events.js:86:13)                                                                                                   
    at TLSSocket.emit (events.js:185:7)                                                                                             
    at emitReadable_ (_stream_readable.js:432:10)                                                                                   
    at emitReadable (_stream_readable.js:426:7)                                                                                     
    at readableAddChunk (_stream_readable.js:187:13)                                                                                
    at TLSSocket.Readable.push (_stream_readable.js:134:10)                                                                         
    at TLSWrap.onread (net.js:548:20)                                                                                               
    at Socket.ondata (_stream_wrap.js:58:20)                                                                                        
    at emitOne (events.js:96:13)                                                                                                    
    at Socket.emit (events.js:188:7)                                                                                                
```

Node-RED is now unstartable. I'll have to revert to the backup flow file.

**Comment by JonSilver** [comment]
Me too. I managed to remove the email node from the flows file by editing in a text editor so node-red can restart. But I'm still short of a way to receive email messages into node-red conveniently.

**Comment by mrummuka** [comment]
I got the same error in node-red v14.6 in linux but with slightly different symptoms - my node-red crashes too but restart works without problems and also email in node resumes working after node-red has been brought up.
```

18 Mar 02:31:06 - TypeError: Cannot set property 'name' of undefined
    at Connection.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:426:22)
    at Connection._resTagged (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:1530:22)
    at Parser.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:193:10)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._resTagged (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/usr/local/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)

```

**Comment by dosknoblauch** [comment]
same for me:

I got every time crach, if I want to receive mail from google.
Sometimes I see them in debugging node, but some seconds later everything is down. node red tries to restart everytime.
Only solution is to edit the .json file, so that node red can now connect.

node red: v.0.16.2  on raspberrypi, raspbian
