### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by Roaders** [node-red/node-red-nodes#302]
I get this when I startup node red:

```
19 Apr 06:52:47 - TypeError: Cannot read property 'device' of undefined
at /home/pi/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:128:38
at Parser.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
at Parser.emit (events.js:95:17)
at Object.onclosetag (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
at emit (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
at emitNode (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
at closeTag (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
at Object.write (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/node_modules/sax/lib/sax.js:1452:13)
at Parser.exports.Parser.Parser.parseString (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
at Parser.parseString (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
at Object.exports.parseString (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/xml2js/lib/xml2js.js:540:19)
at Request._callback (/home/pi/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:125:16)
at Request.self.callback (/home/pi/.node-red/node_modules/node-red-node-wemo/node_modules/request/request.js:187:22)
at Request.emit (events.js:98:17)
```

I am on node red version 13 something or other.
I have had this on and off a little bit. I have had some success with removing and re-installing the npm module but that isn't working this time round...

**Comment by Roaders** [comment]
Sorry, I don't know why I got here when I was looking for the wemo node!!! Will post on the correct repo!

**Comment by hardillb** [comment]
This is the right repo. The wemo nodes are in node-red-nodes/hardware/wemo

**Comment by hardillb** [comment]
You shouldn't need to reinstall to work round this.

This error means that a WeMo device has responded to the uPnP request with a empty response.

How often do you see it? Are you only using real WeMo devices or are you using the node that emulates sockets or other hardware pretending to be a device?

**Comment by hardillb** [comment]
Double check you have version 0.1.11 of the node as there should already be a check for this.

**Comment by Roaders** [comment]
I definitely do have version 0.1.11 but they line in question did not check for `json.root`, it just checked for `!err` and `json`.
Adding the check for root fixed this.

**Comment by Roaders** [comment]
Yup, the code here:

https://github.com/node-red/node-red-nodes/blob/master/hardware/wemo/lib/wemo.js

does not check for `json.root` either

**Comment by hardillb** [comment]
yeah, I thought I'd fixed this in the last release, but must have missed it and it's not happened at home recently (since I changed the wifi channel to something less crowded).

I'll push a update soon

**Comment by Roaders** [comment]
Thanks, I would do a PR but can't do that till I get home and unlikely to have time tonight!

**Comment by Roaders** [comment]
I see the new release `0.1.13` but when I npm install I still get `0.1.11`... odd..

**Comment by dceejay** [comment]
try `npm i node-red-node-wemo@0.1.13`
