### ISSUE TITLE
possible memory leak in node-pushbullet

### ISSUE THREAD

**Issue by mrummuka** [node-red/node-red-nodes#327]
4 Jun 08:40:31 - [info] Starting modified flows
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at PushbulletConfig.onConfig (/usr/local/lib/node_modules/node-red-node-pushbullet/57-pushbullet.js:119:22)
    at new PushbulletOut (/usr/local/lib/node_modules/node-red-node-pushbullet/57-pushbullet.js:350:24)
    at createNode (/usr/local/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)
    at Flow.start (/usr/local/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/local/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:264:29)
    at /usr/local/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:121:25
    at tryCatchReject (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by dceejay** [comment]
any more context to this ? Which version of Node-RED ? 
How many pushbullet nodes are you using ?
What provoked it ? Did you redeploy several times before it did this...
more clues appreciated.

**Comment by mrummuka** [comment]
> any more context to this ? 
Sure, sorry about that.

> Which version of Node-RED ?
4 Jun 12:16:51 - [info] Node-RED version: v0.14.6
4 Jun 12:16:51 - [info] Node.js  version: v4.2.6
4 Jun 12:16:51 - [info] Linux 4.4.0-31-generic x64 LE
4 Jun 12:16:51 - [info] Loading palette nodes


> How many pushbullet nodes are you using ?
Two, in one flow. But other flow (not related) running on same instance.

> What provoked it ? 
Can't really tell (I don't know). Just noticed this on logs looking for clues for other (probably unrelated: https://github.com/windkh/node-red-contrib-telegrambot/issues/19) error. 

> Did you redeploy several times before it did this...
I think so, but cannot really confirm, as  my workflow has been more or less "edit-deploy-edit-deploy-edit-deploy" and sometimes restart.

> more clues appreciated.
Anything else I should/could look into?

**Comment by dceejay** [comment]
Actually this is just a warning - albeit a pain in the....
I can up the default limit from 10 to see if that helps.
but it should be non-fatal.

**Comment by DerMattes** [comment]
Hi, just found this over google, I know its quite old.

I have this error and it is fatal, pushbullet messages are not sent or received after this error occurs in the log.
I want to try emitter.setMaxListeners() but don't know where to set this? Any help is much appreciated.

I am using node red in home assistant with the hass.io addon.

**Comment by dceejay** [comment]
try looking at line 113

**Comment by DerMattes** [comment]
> try looking at line 113

I imagine this is a reference to some config or source code file?

**Comment by dceejay** [comment]
sorry - as you added to this already closed topic I assumed you had looked at the files it had changed above...
![image](https://user-images.githubusercontent.com/5375409/51933898-46e94680-23fa-11e9-922f-f2615861e263.png)
