### ISSUE TITLE
node-red-node-serialport/serialport not found

### ISSUE THREAD

**Issue by QAnders** [node-red/node-red-nodes#404]
Raised a first Issue here, https://github.com/node-serialport/node-serialport/issues/1471, but my serialport works fine "stand-alone".

Running on RaspberryPI 3 with Node v9.5.0:

```
Welcome to Node-RED
===================
8 Feb 06:10:37 - [info] Node-RED version: v0.18.2
8 Feb 06:10:37 - [info] Node.js  version: v4.2.1
8 Feb 06:10:37 - [info] Linux 4.9.59-v7+ arm LE
8 Feb 06:10:38 - [info] Loading palette nodes
8 Feb 06:10:41 - [info] Dashboard version 2.8.0 started at /ui
It looks like serialport didn't compile properly. This is a common problem and its fix is well documented here https://github.com/voodootikigod/node-serialport#to-install
The result of requiring the package is:  undefined
8 Feb 06:10:44 - [warn] ------------------------------------------------------
8 Feb 06:10:44 - [warn] [node-red-node-serialport/serialport] Error: Module version mismatch. Expected 46, got 59.
8 Feb 06:10:44 - [warn] [node-red-node-arduino/arduino] Missing serialport dependency
8 Feb 06:10:44 - [warn] ------------------------------------------------------
8 Feb 06:10:44 - [info] Settings file  : /home/pi/.node-red/settings.js
8 Feb 06:10:44 - [info] User directory : /home/pi/.node-red
8 Feb 06:10:44 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
8 Feb 06:10:44 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
8 Feb 06:10:44 - [info] Server now running at http://127.0.0.1:1880/
8 Feb 06:10:44 - [info] Waiting for missing types to be registered:
8 Feb 06:10:44 - [info]  - arduino-board (provided by npm module node-red-node-arduino)
8 Feb 06:10:44 - [info]  - arduino in (provided by npm module node-red-node-arduino)
8 Feb 06:10:44 - [info] To install any of these missing modules, run:
8 Feb 06:10:44 - [info]   npm install <module name>
8 Feb 06:10:44 - [info] in the directory:
8 Feb 06:10:44 - [info]   /home/pi/.node-red
```

**Comment by dceejay** [comment]
You say node 9.5.  But the log shows node 4.2.1
And the serialport is complaining a out a version mismatch... 
As is the error.
You could try our upgrade script as per the  install docs for pi.

**Comment by QAnders** [comment]
Thanks for getting back to me so quickly!

Not sure why Node-Red insists on starting with an older version of Node... 
I am not that familiar with Node.js and all the versioning, sorry...
The version output on my R-Pi is:
```
pi@raspberrypi:~/.node-red $ nvm current
v9.5.0
pi@raspberrypi:~/.node-red $ node -v
v9.5.0
pi@raspberrypi:~/.node-red $ npm -v
5.6.0
```

When I start node-red using `node-red-start` it uses v4.2.1 though...

I also now tried to run a script using serial port in the .node-red directory and then I get this error:
```
Error: The module '/home/pi/.node-red/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at bindings (/home/pi/.node-red/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/serialport/lib/bindings/linux.js:2:36)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```
Seems that if I run teh script outside of .node-red it is using teh global serialport (which works) but inside .node-red it is using teh "local" module (which fails).

**Comment by QAnders** [comment]
And, yes, I followed the upgrade instructions for Node-red, forgot to mention that.

At first I had:
```
pi@raspberrypi:~/.node-red $ npm outdated
Package     Current  Wanted  Latest  Location
serialport    6.0.5   6.1.0   6.0.5  node-red-project
```

Then I installed serialport "hard" as:
`sudo npm install serialport@6.1.0 --unsafe-perm --build-from-source`

(Only `sudo` works for installing serialport)

After this I get:
```
pi@raspberrypi:~/.node-red $ npm outdated
Package     Current  Wanted  Latest  Location
serialport    6.1.0   6.1.0   6.0.5  node-red-project
```

However, Node-Red still starts with v4.2.1 of Node.js...

**Comment by QAnders** [comment]
I found that there was a "default" Node.js installed through apt-get on my R-Pi so I removed that using apt-get and now there (should) be only the Node.js which I've added through `nvm`.

However, trying to install node-red again through the "upgrade" process I can see this in the install log:
```
wanted: {"node":">=4.5.0"} (current: {"node":"4.2.1","npm":"2.14.7"})
```
Where does this come from that Node-red keeps referencing and using v4.2.1?
It is driving me insane...

**Comment by QAnders** [comment]
I found, and ran, ´update-nodejs-and-nodered´.
It reports: 
```
Running Node-RED update for user pi at /home/pi

This can take 20-30 minutes on the slower Pi versions - please wait.

  Stop Node-RED                       ?
  Remove old version of Node-RED      ?
  Using NVM to manage Node.js         +   please run   nvm use lts/*   before running ./node-reds                     
  Update Node.js LTS                  ?   Node v9.5.0   Npm 5.6.0
  Clean npm cache                     ?
  Install Node-RED core               ?   0.18.2 
  Move global nodes to local          ?
  Install extra Pi nodes              -
  Npm rebuild existing nodes          ?
  Add menu shortcut                   ?
  Update systemd script               ?
  Update update script                ?
Any errors will be logged to   /var/log/nodered-install.log


All done.
```
NVM gives:
```
pi@raspberrypi:~/.node-red $ nvm current
v9.5.0
```
Now everything is messed up though...
```
Starting as a systemd service.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
Started Node-RED graphical event wiring tool..
nodered.service: Main process exited, code=exited, status=127/n/a
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
...
...
...
...
```

**Comment by dceejay** [comment]
Yeah nvm is a pita. 
Yes it makes the environment per user and also per instance.
If at all possible I'd advise against using it. 
Also we recommend node LTS which is 8.x rather than 9

**Comment by QAnders** [comment]
I've crawled back to the original now and reflashed with a "clean" Raspian...
No `nvm` installed and Node version is v4.8.2 by default. Node-Red running and Serial port Node available and working.
Ran a  `sudo apt-get install nodejs npm node-semver` to get `npm` in there and after a reboot I have a working serilaport again...

Now I just need to figure out how to get AWS-SDK running whitout wrecking everything else again...

**Comment by dceejay** [comment]
So now running the upgrade script ( not as root) should get you to node 8 and latest node-red

**Comment by dceejay** [comment]
you OK now ? can we close this ?

**Comment by QAnders** [comment]
I haven't dared to upgrade, but sure, we'll close!
Thanks for your support!
