### ISSUE TITLE
Node-red crashes with email node

### ISSUE THREAD

**Issue by feltspar** [node-red/node-red-nodes#461]
Posted on discourse but advised to raise issue here by @knolleary 

I have a simple email node and debug-node set-up within a web application using node red. 
The email node has refresh time set to 5 seconds, protocol: IMAP. 
I have a gmail account logged in. I am sending emails from the same and a different email account. 

Node-red crashes with the error given below: (Happens rather quickly when I receive an email with an attachment of > 10mb. But happens without attachments as well), though seems to take longer sometimes.

The TypeError is on different properties like 'name', 'type' '11456', 'cbargs' etc...

```
10 Jul 17:00:28 - [info] Starting flows
10 Jul 17:00:28 - [info] Started flows
10 Jul 17:00:37 - [red] Uncaught Exception:
10 Jul 17:00:37 - TypeError: Cannot set property 'name' of undefined
    at Connection.<anonymous> (/usr/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:431:22)
    at Connection._resTagged (/usr/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/usr/lib/node_modules/node-red/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser._resTagged (/usr/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/usr/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/usr/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/usr/lib/node_modules/node-red/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:106:13)
```

Versions:

```
10 Jul 17:00:27 - [info] Node-RED version: v0.18.7
10 Jul 17:00:27 - [info] Node.js  version: v8.11.3
10 Jul 17:00:27 - [info] Linux 4.15.0-24-generic x64 LE
```
Package.json :

```
"dependencies": {
    "imap": "^0.8.19",
    "mailparser": "^0.6.2",
    "nodemailer": "^1.11.0",
```

On restarting node red. The email node resumes working but fails again soon after. 

Thanks in advance!

**Comment by BerndGewehr** [comment]
My node red vanilla install crashes immediately when I use the email node with imap SSL against IBM Smartcloud notes.

**Comment by BerndGewehr** [comment]
Can we force a newer Version to be used that doesn’t crash due to unhandled exceptions?

**Comment by BerndGewehr** [comment]
Here my crash report:

`2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT 30 Aug 07:34:47 - [red] Uncaught Exception:
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT 30 Aug 07:34:47 - TypeError: Cannot read property 'to' of undefined
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at processNewMessage (/home/vcap/app/node_modules/node-red-node-email/61-email.js:196:51)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at MailParser.<anonymous> (/home/vcap/app/node_modules/node-red-node-email/61-email.js:354:41)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at emitOne (events.js:96:13)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at MailParser.emit (events.js:188:7)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at runCallback (timers.js:672:20)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at tryOnImmediate (timers.js:645:5)
   2018-08-30T09:34:47.87+0200 [APP/PROC/WEB/0] OUT     at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by BerndGewehr** [comment]
I guess the json operations should be in try...catch to avoid this type of error:

in https://github.com/node-red/node-red-nodes/blob/master/social/email/61-email.js

```
192        function processNewMessage(msg, mailMessage) {
193            msg = JSON.parse(JSON.stringify(msg)); // Clone the message
194            // Populate the msg fields from the content of the email message
195            // that we have just parsed.
```

**Comment by BerndGewehr** [comment]
Couldn't we just use

```
        function processNewMessage(msg, mailMessage) {
            msg = JSON.parse(JSON.stringify(msg)); // Clone the message
            // Populate the msg fields from the content of the email message
            // that we have just parsed.
->     try{
            msg.payload = mailMessage.text;
            msg.topic = mailMessage.subject;
            msg.date = mailMessage.date;
            msg.header = mailMessage.headers;
            if (mailMessage.html) { msg.html = mailMessage.html; }
            if (mailMessage.to && mailMessage.from.to > 0) { msg.to = mailMessage.to; }
            if (mailMessage.cc && mailMessage.from.cc > 0) { msg.cc = mailMessage.cc; }
            if (mailMessage.bcc && mailMessage.from.bcc > 0) { msg.bcc = mailMessage.bcc; }
            if (mailMessage.from && mailMessage.from.length > 0) { msg.from = mailMessage.from[0].address; }
           if (mailMessage.attachments) { msg.attachments = mailMessage.attachments; }
            else { msg.attachments = []; }
->      }catch(e){
            console.log("YO",e)
           }
           node.send(msg); // Propagate the message down the flow
       } // End of processNewMessage
```

to avoid the crash, @dceejay ?

**Comment by dceejay** [comment]
No - I think the issue is actually the bad code - see #442

pushed as version 1.0.1

**Comment by BerndGewehr** [comment]
@dceejay do you really think that was enough?

```
        function processNewMessage(msg, mailMessage) {
            msg = JSON.parse(JSON.stringify(msg)); // Clone the message
            // Populate the msg fields from the content of the email message
            // that we have just parsed.
            msg.payload = mailMessage.text;
            msg.topic = mailMessage.subject;
            msg.date = mailMessage.date;
            msg.header = mailMessage.headers;
            if (mailMessage.html) { msg.html = mailMessage.html; }
            if (mailMessage.to && mailMessage.from.to > 0) { msg.to = mailMessage.to; }
            if (mailMessage.cc && mailMessage.from.cc > 0) { msg.cc = mailMessage.cc; }
            if (mailMessage.bcc && mailMessage.from.bcc > 0) { msg.bcc = mailMessage.bcc; }
            if (mailMessage.from && mailMessage.from.length > 0) { msg.from = mailMessage.from[0].address; }
            if (mailMessage.attachments) { msg.attachments = mailMessage.attachments; }
            else { msg.attachments = []; }
            node.send(msg); // Propagate the message down the flow
        } // End of processNewMessage
```

Shouldn't it be 

```
        function processNewMessage(msg, mailMessage) {
            msg = JSON.parse(JSON.stringify(msg)); // Clone the message
            // Populate the msg fields from the content of the email message
            // that we have just parsed.
            msg.payload = mailMessage.text;
            msg.topic = mailMessage.subject;
            msg.date = mailMessage.date;
            msg.header = mailMessage.headers;
            if (mailMessage.html) { msg.html = mailMessage.html; }
            if (mailMessage.to && mailMessage.to.length > 0) { msg.to = mailMessage.to; }
            if (mailMessage.cc && mailMessage.cc.length > 0) { msg.cc = mailMessage.cc; }
            if (mailMessage.bcc && mailMessage.bcc.length > 0) { msg.bcc = mailMessage.bcc; }
            if (mailMessage.from && mailMessage.from.length > 0) { msg.from = mailMessage.from[0].address; }
            if (mailMessage.attachments) { msg.attachments = mailMessage.attachments; }
            else { msg.attachments = []; }
            node.send(msg); // Propagate the message down the flow
        } // End of processNewMessage

**Comment by dceejay** [comment]
you looking at the correct version ? it is as you said

            if (mailMessage.to && mailMessage.to.length > 0) { msg.to = mailMessage.to; }
            if (mailMessage.cc && mailMessage.cc.length > 0) { msg.cc = mailMessage.cc; }
            if (mailMessage.bcc && mailMessage.bcc.length > 0) { msg.bcc = mailMessage.bcc; }

**Comment by BerndGewehr** [comment]
True. I saw a state of the code in between the commits. Thank you very much!

**Comment by BerndGewehr** [comment]
Well, I see this code after my last update:

```
  function processNewMessage(msg, mailMessage) {
            msg = JSON.parse(JSON.stringify(msg)); // Clone the message
            // Populate the msg fields from the content of the email message
            // that we have just parsed.
            msg.payload = mailMessage.text;
            msg.topic = mailMessage.subject;
            msg.date = mailMessage.date;
            msg.header = mailMessage.headers;
            if (mailMessage.html) { msg.html = mailMessage.html; }
            if (mailMessage.to && mailMessage.from.to > 0) { msg.to = mailMessage.to; }
            if (mailMessage.cc && mailMessage.from.cc > 0) { msg.cc = mailMessage.cc; }
            if (mailMessage.bcc && mailMessage.from.bcc > 0) { msg.bcc = mailMessage.bcc; }
            if (mailMessage.from && mailMessage.from.length > 0) { msg.from = mailMessage.from[0].address; }
            if (mailMessage.attachments) { msg.attachments = mailMessage.attachments; }
            else { msg.attachments = []; }
            node.send(msg); // Propagate the message down the flow
        } // End of processNewMessage
```

That's why I asked.

**Comment by BerndGewehr** [comment]
Now I got it.

**Comment by dceejay** [comment]
but - yes - if it's still crashing - please post the error...
and maybe add a line  ` console.log(msg,mailMessage);` just before the clone line 193, and report what it shows.

**Comment by BerndGewehr** [comment]
My node red still pulls 0.1.29 and the manage palette update does not update, saying "module not locally installed" on my IBM Bluemix node red boilerplate. Any hints on how to update? Already tried all i know...

**Comment by dceejay** [comment]
you need to update the package.json in your project - to point to the 1.x version - and ensure you are using node 8.x - then when you push it / restage it it will build with the latest version
