### ISSUE TITLE
XMPP in node crashes node-red...

### ISSUE THREAD

**Issue by hermannw** [node-red/node-red-nodes#507]
...when the field "Buddy" is not empty!
I have been testing the XMPP nodes for a few days and found that this a repeatable pattern.
See log extract below.
I am using Cisco Jabber on a Windows 10 PC and on an iPhone to send the messages.

### Which node are you reporting an issue on?
XMPP in
### What are the steps to reproduce?
Add XMP in node and connect two debug nodes.
Leave the field "Buddy" empty and everything works ok, fill something in and node-red crashes (or restarts since I am using PM2)
### What happens?
Node-red crashes when a message comes in. See log below.
### What do you expect to happen?
Send out the received message
### Please tell us about your environment:

- [ ] Node-RED version: 0.19.4
- [ ] node.js version: 6.15.0 
- [ ] npm version: 6.4.1
- [ ] Platform/OS:  Linux 4.14.70-sunxi arm LE, Armbian on OrangePi PC+
- [ ] Browser: FF, Chrome

Extract from PM2 log nodered:
```
| ReferenceError: from is not defined
|     at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-xmpp/92-xmpp.js:104:81)
|     at emitOne (events.js:96:13)
|     at EventEmitter.emit (events.js:188:7)
|     at Client.<anonymous> (/home/pi/.node-red/node_modules/simple-xmpp/lib/simple-xmpp.js:325:20)
|     at emitOne (events.js:96:13)
|     at Client.emit (events.js:188:7)
|     at Client._handleStanza (/home/pi/.node-red/node_modules/node-xmpp-client/lib/Client.js:227:12)
|     at Client.onStanza (/home/pi/.node-red/node_modules/node-xmpp-client/lib/Client.js:221:8)
|     at emitOne (events.js:96:13)
|     at Connection.emit (events.js:188:7)
|     at Connection.onStanza (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:377:10)
|     at StreamParser.<anonymous> (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:231:10)
|     at emitOne (events.js:96:13)
|     at StreamParser.emit (events.js:188:7)
|     at SaxLtx.<anonymous> (/home/pi/.node-red/node_modules/@xmpp/streamparser/index.js:69:14)
|     at emitOne (events.js:96:13)
| 1 Dec 18:39:20 - [red] Uncaught Exception:
| 1 Dec 18:39:20 - ReferenceError: from is not defined
|     at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-xmpp/92-xmpp.js:104:81)
|     at emitOne (events.js:96:13)
|     at EventEmitter.emit (events.js:188:7)
|     at Client.<anonymous> (/home/pi/.node-red/node_modules/simple-xmpp/lib/simple-xmpp.js:325:20)
|     at emitOne (events.js:96:13)
|     at Client.emit (events.js:188:7)
|     at Client._handleStanza (/home/pi/.node-red/node_modules/node-xmpp-client/lib/Client.js:227:12)
|     at Client.onStanza (/home/pi/.node-red/node_modules/node-xmpp-client/lib/Client.js:221:8)
|     at emitOne (events.js:96:13)
|     at Connection.emit (events.js:188:7)
|     at Connection.onStanza (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:377:10)
|     at StreamParser.<anonymous> (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:231:10)
|     at emitOne (events.js:96:13)
|     at StreamParser.emit (events.js:188:7)
|     at SaxLtx.<anonymous> (/home/pi/.node-red/node_modules/@xmpp/streamparser/index.js:69:14)
|     at emitOne (events.js:96:13)
```
I un-commented line 95 in 92-xmpp.js and this is the output - if it helps...
```
Stanza {
   name: 'message',
   parent: null,
   children:
    [ Element {
        name: 'composing',
        parent: [Circular],
        children: [],
        attrs: [Object] } ],
   attrs:
    { to: 'wwww@blah.im',
      from: 'name@mycompany.com/jabber_1469250000',
      'xml:lang': 'en',
      type: 'chat',
      'xmlns:stream': 'http://etherx.jabber.org/streams' } }
 Stanza {
   name: 'message',
   parent: null,
   children:
    [ Element {
        name: 'body',
        parent: [Circular],
        children: [Object],
        attrs: {} },
      Element {
        name: 'thread',
       parent: [Circular],
        children: [Object],
        attrs: {} },
      Element {
        name: 'html',
        parent: [Circular],
        children: [Object],
        attrs: [Object] },
      Element {
        name: 'active',
        parent: [Circular],
        children: [],
        attrs: [Object] },
      Element {
        name: 'stanza-id',
        parent: [Circular],
        children: [],
        attrs: [Object] } ],
   attrs:
    { to: 'wwww@blah.im',
      from: 'name@mycompany.com/jabber_1469250000',
      id: '79d84cd1:0c36:40ba:8478:5abcafa6bf5a',
      type: 'chat',
      'xml:lang': 'en',
      'xmlns:stream': 'http://etherx.jabber.org/streams' } }
```

**Comment by TheCapsLock** [comment]
I think we can replace [line 104](https://github.com/node-red/node-red-nodes/blob/master/social/xmpp/92-xmpp.js#L104) as followed:

```diff
- if (!node.join && ((node.from === "") || (node.from === from))) {
+ if (!node.join && ((node.from === "") || (node.from === stanza.attrs.from))) {
```

**Comment by dceejay** [comment]
Hi yes - that may indeed help. Do you want raise a PR - or shall I patch manually ?
Happy either way.

**Comment by dceejay** [comment]
Patched - so closing
