### ISSUE TITLE
pushover node crashes if there is no internet connection

### ISSUE THREAD

**Issue by tve** [node-red/node-red-nodes#548]
### Which node are you reporting an issue on?

pushover

### What are the steps to reproduce?

send a message while there is no internet connection and their server cannot be dns-resolved

### What happens?

Crash log:
```
17 Jun 10:35:20 - [error] [pushover:1359c31a.d255fd] [57-pushover.js] Error: Error: getaddrinfo ENOTFOUND api.pushover.net api.pushover.net:443
17 Jun 10:35:20 - [red] Uncaught Exception:
17 Jun 10:35:20 - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/src/node-red/node_modules/node-red-node-pushover/57-pushover.js:103:33
    at ClientRequest.<anonymous> (/usr/src/node-red/node_modules/pushover-notifications/lib/pushover.js:254:7)
```
A possible solution is to place the JSON.parse into a try/catch clause at https://github.com/node-red/node-red-nodes/blob/master/social/pushover/57-pushover.js#L103

### What do you expect to happen?

Node-red not to crash...

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.5
- [ ] node.js version: v8
- [ ] npm version:
- [ ] Platform/OS: linux
- [ ] Browser: chrome

**Comment by tve** [comment]
Thanks!!

**Comment by atompie** [comment]
26 Oct 12:09:32 - SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Pushover.errors (/home/risto/.node-red/node_modules/pushover-notifications/lib/pushover.js:134:14)
    at IncomingMessage.<anonymous> (/home/risto/.node-red/node_modules/pushover-notifications/lib/pushover.js:241:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

This error crashed the whole node-red service.

**Comment by dceejay** [comment]
that is a bug in the pushover library - they aren't catching that error locally - and as they throw it asynchronously we can't catch it. So you will need to raise that as an issue against the library

    https://github.com/qbit/node-pushover/blob/master/lib/pushover.js#L134
