### ISSUE TITLE
node-red-node-sqlite 0.4.0 - Install fails on HassOS 3.5 / Home Assistant 0.100.2 / Node-RED 4.2.1

### ISSUE THREAD

**Issue by NobleKangaroo** [node-red/node-red-nodes#582]
### Which node are you reporting an issue on?
node-red-node-sqlite 0.4.0

### What are the steps to reproduce?
1. Install HassIO 3.5 on RasPi 4 (https://www.home-assistant.io/hassio/installation/)
2. Install, configure, and start Let's Encrypt addon (obtaining a valid certificate)
3. Install, configure, and start Node-RED addon
4. Open Node-RED UI, go to "Manage palette", attempt node-red-node-sqlite install

### What happens?
Errors during install, installation fails:
```
-----------------------------------------------------------
2019-10-15T02:05:11.291Z Install : node-red-node-sqlite 0.4.0

2019-10-15T02:05:16.029Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-sqlite@0.4.0
2019-10-15T02:05:30.345Z [out] 
2019-10-15T02:05:30.345Z [out] > sqlite3@4.1.0 install /config/node-red/node_modules/sqlite3
2019-10-15T02:05:30.345Z [out] > node-pre-gyp install --fallback-to-build
2019-10-15T02:05:30.345Z [out] 
2019-10-15T02:05:31.330Z [err] node-pre-gyp
2019-10-15T02:05:31.332Z [err]  
2019-10-15T02:05:31.332Z [err] WARN
2019-10-15T02:05:31.332Z [err]  Using request for node-pre-gyp https download
2019-10-15T02:05:31.332Z [err]  
2019-10-15T02:05:31.748Z [err] node-pre-gyp
2019-10-15T02:05:31.748Z [err]  WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v64-linux-arm.tar.gz 
2019-10-15T02:05:31.748Z [err] node-pre-gyp
2019-10-15T02:05:31.748Z [err]  WARN 
2019-10-15T02:05:31.749Z [err] Pre-built binaries not found for sqlite3@4.1.0 and node@10.16.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
2019-10-15T02:05:35.743Z [err] gyp
2019-10-15T02:05:35.746Z [err]  
2019-10-15T02:05:35.746Z [err] ERR!
2019-10-15T02:05:35.746Z [err]  build error
2019-10-15T02:05:35.746Z [err]  
2019-10-15T02:05:35.748Z [err] gyp
2019-10-15T02:05:35.748Z [err]  ERR! stack
2019-10-15T02:05:35.748Z [err]  Error: not found: make
2019-10-15T02:05:35.748Z [err] gyp ERR!
2019-10-15T02:05:35.748Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-10-15T02:05:35.748Z [err] gyp 
2019-10-15T02:05:35.748Z [err] ERR! stack
2019-10-15T02:05:35.748Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-10-15T02:05:35.748Z [err] gyp
2019-10-15T02:05:35.748Z [err]  ERR! 
2019-10-15T02:05:35.749Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-10-15T02:05:35.749Z [err] gyp
2019-10-15T02:05:35.749Z [err]  ERR! stack
2019-10-15T02:05:35.749Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-10-15T02:05:35.749Z [err] gyp 
2019-10-15T02:05:35.749Z [err] ERR! stack
2019-10-15T02:05:35.749Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-10-15T02:05:35.749Z [err] gyp 
2019-10-15T02:05:35.749Z [err] ERR! stack
2019-10-15T02:05:35.749Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-10-15T02:05:35.749Z [err] gyp
2019-10-15T02:05:35.749Z [err]  ERR! 
2019-10-15T02:05:35.750Z [err] stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-10-15T02:05:35.750Z [err] gyp
2019-10-15T02:05:35.750Z [err]  ERR! System
2019-10-15T02:05:35.750Z [err]  Linux 4.19.71-v7l
2019-10-15T02:05:35.751Z [err] gyp
2019-10-15T02:05:35.751Z [err]  ERR! 
2019-10-15T02:05:35.751Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
2019-10-15T02:05:35.751Z [err] gyp
2019-10-15T02:05:35.751Z [err]  ERR!
2019-10-15T02:05:35.751Z [err]  cwd /config/node-red/node_modules/sqlite3
2019-10-15T02:05:35.751Z [err] gyp 
2019-10-15T02:05:35.751Z [err] ERR! 
2019-10-15T02:05:35.751Z [err] node -v v10.16.3
2019-10-15T02:05:35.752Z [err] gyp 
2019-10-15T02:05:35.752Z [err] ERR! node-gyp -v
2019-10-15T02:05:35.752Z [err]  v3.8.0
2019-10-15T02:05:35.752Z [err] gyp 
2019-10-15T02:05:35.752Z [err] ERR! not ok
2019-10-15T02:05:35.752Z [err]  
2019-10-15T02:05:35.756Z [err] node-pre-gyp
2019-10-15T02:05:35.757Z [err]  ERR! build error
2019-10-15T02:05:35.757Z [err]  
2019-10-15T02:05:35.758Z [err] node-pre-gyp
2019-10-15T02:05:35.758Z [err]  ERR! stack
2019-10-15T02:05:35.758Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2019-10-15T02:05:35.758Z [err] node-pre-gyp 
2019-10-15T02:05:35.758Z [err] ERR! stack
2019-10-15T02:05:35.758Z [err]      at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2019-10-15T02:05:35.758Z [err] node-pre-gyp 
2019-10-15T02:05:35.758Z [err] ERR! stack
2019-10-15T02:05:35.758Z [err]      at ChildProcess.emit (events.js:198:13)
2019-10-15T02:05:35.758Z [err] node-pre-gyp
2019-10-15T02:05:35.759Z [err]  ERR! 
2019-10-15T02:05:35.759Z [err] stack     at maybeClose (internal/child_process.js:982:16)
2019-10-15T02:05:35.759Z [err] node-pre-gyp ERR!
2019-10-15T02:05:35.759Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2019-10-15T02:05:35.760Z [err] node-pre-gyp
2019-10-15T02:05:35.760Z [err]  ERR! System
2019-10-15T02:05:35.760Z [err]  Linux 4.19.71-v7l
2019-10-15T02:05:35.760Z [err] node-pre-gyp
2019-10-15T02:05:35.760Z [err]  ERR!
2019-10-15T02:05:35.760Z [err]  command
2019-10-15T02:05:35.760Z [err]  "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2019-10-15T02:05:35.761Z [err] node-pre-gyp 
2019-10-15T02:05:35.761Z [err] ERR! 
2019-10-15T02:05:35.761Z [err] cwd /config/node-red/node_modules/sqlite3
2019-10-15T02:05:35.761Z [err] node-pre-gyp ERR!
2019-10-15T02:05:35.761Z [err]  node -v
2019-10-15T02:05:35.761Z [err]  v10.16.3
2019-10-15T02:05:35.761Z [err] node-pre-gyp 
2019-10-15T02:05:35.761Z [err] ERR! node-pre-gyp -v
2019-10-15T02:05:35.761Z [err]  v0.11.0
2019-10-15T02:05:35.761Z [err] node-pre-gyp ERR!
2019-10-15T02:05:35.762Z [err]  not ok
2019-10-15T02:05:35.762Z [err]  
2019-10-15T02:05:35.763Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2019-10-15T02:05:36.407Z [err] npm
2019-10-15T02:05:36.407Z [err]  ERR! code ELIFECYCLE
2019-10-15T02:05:36.408Z [err] npm
2019-10-15T02:05:36.408Z [err]  ERR! 
2019-10-15T02:05:36.408Z [err] errno 1
2019-10-15T02:05:36.411Z [err] npm
2019-10-15T02:05:36.411Z [err]  ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
2019-10-15T02:05:36.411Z [err] npm 
2019-10-15T02:05:36.411Z [err] ERR! Exit status 1
2019-10-15T02:05:36.412Z [err] npm
2019-10-15T02:05:36.412Z [err]  ERR! 
2019-10-15T02:05:36.412Z [err] npm 
2019-10-15T02:05:36.412Z [err] ERR! Failed at the sqlite3@4.1.0 install script.
2019-10-15T02:05:36.412Z [err] npm
2019-10-15T02:05:36.413Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-15T02:05:36.578Z [err] 
2019-10-15T02:05:36.579Z [err] npm ERR!
2019-10-15T02:05:36.579Z [err]  A complete log of this run can be found in:
2019-10-15T02:05:36.579Z [err] npm ERR!
2019-10-15T02:05:36.579Z [err]      /root/.npm/_logs/2019-10-15T02_05_36_450Z-debug.log
2019-10-15T02:05:36.596Z rc=1
```

### What do you expect to happen?
node-red-node-sqlite package to be successfully installed

### Please tell us about your environment:
- [ ] **HassOS version:** 3.5 on RasPi 4 (hassos_rpi4-3.5.img.gz)
- [ ] **Home Assistant version:** 0.100.2
- [ ] **Node-RED version:** 4.2.1
- [ ] **node.js version:** 10.16.3
- [ ] **npm version:** 6.9.0
- [ ] **Platform/OS:** HassOS 3.5, running Home Assistant 0.100.2
- [ ] **Browser:** Google Chrome 76.0.3809.100 (Windows 10)

**Comment by hardillb** [comment]
First, 4.2.1 is not a valid Node-RED version (the very latest version of Node-RED is 1.0.2). Look at top of the log output for the correct version number.

Second this isn't actually a problem installing `node-red-node-sqlite` it is with the building of the native component of one of it's dependencies, specifically `sqlite3`.

Looking at the error it looks like you do not have the required build tools installed (e.g. make)

> 
> 15T02:05:35.748Z [err] gyp
> 2019-10-15T02:05:35.748Z [err]  ERR! stack
> 2019-10-15T02:05:35.748Z [err]  Error: not found: make
> 2019-10-15T02:05:35.748Z [err] gyp ERR!

You need to ensure there is a C++ compiler and the supporting tools.

**Comment by dceejay** [comment]
If the pre-req tools to allow building nodes are not installed on the Hassio environment then it's really an issue for them.

**Comment by NobleKangaroo** [comment]
> If the pre-req tools to allow building nodes are not installed on the Hassio environment then it's really an issue for them, or the user to add.
> 
> You could try
> 
> ```
> sudo apt install build-essential python-dev
> cd ~/.node-red
> npm i --unsafe-perm node-red-node-sqlite
> ```
> 
> then stop and restart Node-RED, refresh browser.

Thanks for the reply. In regards to adding build tools, I figured as much. Mainly I just wanted to point a finger at the inability to download pre-built binaries, but if the preferred route is to always have them built then that's absolutely fine.

Appreciate the feedback, have a great one!
&nbsp;

\- NobleKangaroo
