### ISSUE TITLE
Pushover node crashes nodered on server error

### ISSUE THREAD

**Issue by csmale** [node-red/node-red-nodes#590]
### Which node are you reporting an issue on?
pushover
### What are the steps to reproduce?
When pushover.net returns an error (its currently doing that a lot due to ongoing DDos attack)

### What happens?
The node red process crashes:
`26 Oct 11:01:59 - SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Pushover.errors (C:\Users\Colin\.node-red\node_modules\pushover-notifications\lib\pushover.js:134:14)
    at IncomingMessage.<anonymous> (C:\Users\Colin\.node-red\node_modules\pushover-notifications\lib\pushover.js:241:12)
    at IncomingMessage.emit (events.js:193:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)`

### What do you expect to happen?
The error should be logged, but the process should not crash!

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.1
- [ ] node.js version: 11.6.0
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Windows 10 x64
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
This is an asynchronous error thrown by their library - (pushover-notifications). We can't catch it in any meaningful way - they need to handle it and pass it back as an error, rather than throw it asynchronously. Maybe raise an issue on their project ? https://github.com/qbit/node-pushover/issues - they seem to be maintaining it - so should be ok.
I assume you are using latest pushover node ? 0.0.16 ?

**Comment by csmale** [comment]
It looks like it has already been found and fixed upstream in their version 1.2.1.

https://github.com/qbit/node-pushover/pull/26

**Comment by dceejay** [comment]
bumped pre-req and pushed to npm as 0.0.17
