### ISSUE TITLE
Node-RED exited with non-zero exit status 1

### ISSUE THREAD

**Issue by DamianosS** [node-red/node-red-nodes#600]
Hi, Node-RED team!

Node-Red keeps stopping at unspecified intervals. I suspect the email-node (node-red-node-email v 1.7.1); however, it works fine as long the process is running.

Here is the excerpt from the log file ([redmatic.2019-11-07T05_41_21.948Z (1).log](https://github.com/node-red/node-red-nodes/files/3828769/redmatic.2019-11-07T05_41_21.948Z.1.log)

```
Nov  7 01:31:10 ccu3-webui daemon.err node-red: 7 Nov 01:31:10 - [red] Uncaught Exception:
Nov  7 01:31:10 ccu3-webui daemon.err node-red: 7 Nov 01:31:10 - AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
Nov  7 01:31:10 ccu3-webui daemon.err node-red: + expected - actual ... Lines skipped
Nov  7 01:31:10 ccu3-webui daemon.err node-red: - ShutdownWrap {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -   callback: [Function],
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -   handle: TLSWrap {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -     [Symbol(owner)]: TLSSocket {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -       [Symbol(asyncId)]: 7129973,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -       [Symbol(connect-options)]: {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         checkServerIdentity: [Function: checkServerIdentity],
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         host: 'outlook.office365.com',
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         minDHSize: 1024,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         rejectUnauthorized: false,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         singleUse: true,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         socket: Socket {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(asyncId)]: 7129978,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(kBytesRead)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(kBytesWritten)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(lastWriteQueueSize)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(timeout)]: null,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           _events: [Object: null prototype] {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -             close: [
Nov  7 01:31:10 ccu3-webui daemon.err node-red: ...
Nov  7 01:31:10 ccu3-webui daemon.err node-red: + null
Nov  7 01:31:10 ccu3-webui daemon.err node-red: ...
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at JSStreamWrap.doWrite (internal/wrap_js_stream.js:151:12)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at JSStream.onwrite (internal/wrap_js_stream.js:20:57)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.ondata (internal/wrap_js_stream.js:64:22)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.emit (events.js:198:13)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at addChunk (_stream_readable.js:287:12)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at readableAddChunk (_stream_readable.js:268:11)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.Readable.push (_stream_readable.js:223:10)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Nov  7 01:31:10 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
```

Here also the flow in which the email-node is used: [Email.Flow.txt](https://github.com/node-red/node-red-nodes/files/3828767/Email.Flow.txt)

I'm using Node-RED version 1.0 (ported to Homematic as [Redmatic 5.0.2 ](https://github.com/rdmtc/RedMatic)

Please, tell me if you need any further information.
Thanks!

**Comment by PatrickM2201** [comment]
Hello,
today I faced a similar problem like @DamianosS. Node-Red stopped, but in my system it seems to be caused by the alexa-remote2-node (node-red-contrib-alexa-remote2, V3.7.0).
- node.js > V10.18.0
- node-red > V1.0.3 (in Redmatic [https://github.com/rdmtc/RedMatic/releases/tag/v5.3.1](url)
- npm  > V6.13.4
- buildroot/Linux > V2019.11
- Kernel > V4.19.89
- Hardware > RaspberryPi 3B+

Following the extract from the log:
Jan  2 12:05:42 homematic-ccu2 daemon.info node-red[6921]: [alexa-remote-account:cd8daa0b.67814] auto refreshing cookie...
Jan  2 12:05:42 homematic-ccu2 daemon.info node-red[6921]: [alexa-remote-account:cd8daa0b.67814] intialising with the PROXY method and saved data...
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red: 2 Jan 12:05:43 - [red] Uncaught Exception:
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red: 2 Jan 12:05:43 - Error: WebSocket is not open: readyState 2 (CLOSING)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at WebSocket.send (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/ws/lib/websocket.js:329:19)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at Timeout.pingPongInterval.setInterval [as _onTimeout] (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-remote2/alexa-wsmqtt.js:168:36)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at ontimeout (timers.js:436:11)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at tryOnTimeout (timers.js:300:5)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at listOnTimeout (timers.js:263:5)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red:     at Timer.processTimers (timers.js:223:10)
Jan  2 12:05:43 homematic-ccu2 daemon.err node-red: Node-RED exited with non-zero exit status 1

If you need any further information, please contact me.
Thank you

**Comment by knolleary** [comment]
@PatrickM2201 you'll need to report that error against the alexa-remote2 node as that isn't one we maintain in this repo.

**Comment by DamianosS** [comment]
Since I got no response, I switch on the automatic restart of Redmatic in the Debug section. Knowing that this is not a solution, but at least I have no downtimes...

**Comment by PatrickM2201** [comment]
Thanks for your responses,
@knolleary OK, I will report this issue at the alexa-remote2.
@DamianosS Same I have done also, after the error occcured :-)

**Comment by DamianosS** [comment]
Node-RED is terminating about 5-10 times a day, always by throwing the same error.
Anyone who can help?

Thanks!
