### ISSUE TITLE
[red] Uncaught Exception:  TypeError: Cannot read property 's:Body' of undefined.  - Wemo related

### ISSUE THREAD

**Issue by scooterw62** [node-red/node-red-nodes#671]
I've been using the wemo-node for several years. I've got +- 6 plugs.  For the last several months (not sure when it started), I've been seeing node-red crash with the same stack trace below.  I've put in a script to check and restart but I'd like to elliminate the issue. Looking for suggestions to isolate, diagnose, and remove the cause. 
Any suggestions would be appreciated.  Thx. 

Trace: 
11 Aug 09:47:07 - [red] Uncaught Exception:
11 Aug 09:47:07 - TypeError: Cannot read property 's:Body' of undefined
    at /Users/swatson/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:340:44
    at Parser.<anonymous> (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:189:13)
    at SAXParser.onclosetag (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:354:19)
    at IncomingMessage.<anonymous> (/Users/swatson/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:338:14)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

### Which node are you reporting an issue on?
node-red-node-wemo

### What are the steps to reproduce?
Not sure but seems to occur during normal daily use. 

### What happens?
node crash requiring restart - 3-4 times a day

### What do you expect to happen?
catch the exception and continue with notation of the error.  
Suggestions to isolate and/or remove cause. 

### Please tell us about your environment:

- [ ] Node-RED version: v0.19.5
- [ ] node.js version: v10.15.3
- [ ] npm version: 6.4.1 
- [ ] Platform/OS: MacMini - OS 
- [ ] Browser: chrome, safari (IOS and desktop)

**Comment by hardillb** [comment]
Add the following just before line 340 in `/Users/swatson/.node-red/node_modules/node-red-node-wemo/lib/wemo.js`

    console.log(result);

And update this issue with the logged output (it will still crash, but it should show the input data that is causing it to fail)

**Comment by hardillb** [comment]
Actually make the following changes:

```
   res.on('end', function(){
      console.log("raw response %s", data);    //Added
      xml2js.parseString(data, function(err, result){
        console.log(result);    //Added
        if (!err) {  
          var status = result["s:Envelope"]["s:Body"][0]["u:GetBinaryStateResponse"][0]["BinaryState"][0];
          status = parseInt(status);
          def.resolve(status);
        }
      });
    });
```

Where the first line above should be line 337 in the wemo.js file I mentioned earlier.

**Comment by scooterw62** [comment]
Thank you for the quick response.
Will do.

**Comment by scooterw62** [comment]
Hey Ben,
  Good Trap.  It's a "400 Bad Request" causing the event. 
  
---------------------------------------
{ 's:Envelope':
   { '$':
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': [ [Object] ] } }
raw response <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body>
<u:GetBinaryStateResponse xmlns:u="urn:Belkin:service:basicevent:1">
<BinaryState>0</BinaryState>
</u:GetBinaryStateResponse>
</s:Body> </s:Envelope>
{ 's:Envelope':
   { '$':
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': [ [Object] ] } }
raw response <html><body><h1>400 Bad Request</h1></body></html>
{ html: { body: [ [Object] ] } }
14 Aug 06:00:06 - [red] Uncaught Exception:
14 Aug 06:00:06 - TypeError: Cannot read property 's:Body' of undefined
    at /Users/swatson/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:342:44
    at Parser.<anonymous> (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:189:13)
    at SAXParser.onclosetag (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/swatson/.node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/Users/swatson/.node-red/node_modules/xml2js/lib/parser.js:354:19)
    at IncomingMessage.<anonymous> (/Users/swatson/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:339:14)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hardillb** [comment]
OK, there really shouldn't be a reason for the socket to be returning 400 errors, but hey ho.

I've stuck some slightly better error checking in. There is a test build you can try here:

https://www.hardill.me.uk/node-red-node-wemo-0.1.18-beta1.tgz

Let me know how that holds up and I'll get it merged and published if all is good.

**Comment by scooterw62** [comment]
Will do. Thx

**Comment by scooterw62** [comment]
Been running for 2+ days with the candidate patch.  No issues or crashes.
 Looks good.
