### ISSUE TITLE
node-red-node-mongodb version 0.2.1 aggregate broken?

### ISSUE THREAD

**Issue by FotoFieber** [node-red/node-red-nodes#693]
# Which node are you reporting an issue on?
node-red-node-mongodb version 0.2.1

### What are the steps to reproduce?
Node-red flow:
`[{"id":"8de82e5b.fd115","type":"inject","z":"6fec227c.e742dc","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"$match\":{\"$and\":[{\"timestamp\":{\"$lte\":1601299838827}},{\"timestamp\":{\"$gte\":1601213438827}},{\"room\":{\"$eq\":\"bedroom laura\"}},{\"type\":{\"$eq\":\"S_DOOR\"}}]}},{\"$group\":{\"_id\":\"$index\"}}]","payloadType":"json","x":157,"y":201,"wires":[["c50eaccb.f0ac1","3a5a5d64.130512"]]},{"id":"c50eaccb.f0ac1","type":"debug","z":"6fec227c.e742dc","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":384.0093231201172,"y":132.78437042236328,"wires":[]},{"id":"f059a3d9.7f258","type":"debug","z":"6fec227c.e742dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":864,"y":354,"wires":[]},{"id":"2dea4d3.9cdbeb2","type":"mongodb in","z":"6fec227c.e742dc","mongodb":"da814adc.19e598","name":"find state","collection":"STATE","operation":"find","x":440,"y":320,"wires":[["f059a3d9.7f258"]]},{"id":"7f5c8218.66720c","type":"inject","z":"6fec227c.e742dc","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{}","payloadType":"json","x":200,"y":300,"wires":[["2dea4d3.9cdbeb2"]]},{"id":"3a5a5d64.130512","type":"mongodb in","z":"6fec227c.e742dc","mongodb":"da814adc.19e598","name":"aggregate state","collection":"STATE","operation":"aggregate","x":540,"y":200,"wires":[["19f2eda8.5bdef2"]]},{"id":"19f2eda8.5bdef2","type":"debug","z":"6fec227c.e742dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":730,"y":200,"wires":[]},{"id":"da814adc.19e598","type":"mongodb","z":"","hostname":"192.168.66.211","topology":"direct","port":"27017","db":"HASTATE","name":"HASTATE"}]`

### What happens?
I get following payload:
`{"_readableState":{"objectMode":true,"highWaterMark":16,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"_events":{},"_eventsCount":0,"operation":{"options":{"readPreference":{"mode":"primary"}},"ns":{"db":"HASTATE","collection":"$cmd"},"readPreference":{"mode":"primary"},"explain":false,"fullResponse":true,"target":"STATE","pipeline":[{"$match":{"$and":[{"timestamp":{"$lte":1601299838827}},{"timestamp":{"$gte":1601213438827}},{"room":{"$eq":"bedroom laura"}},{"type":{"$eq":"S_DOOR"}}]}},{"$group":{"_id":"$index"}}],"hasWriteStage":false,"cursorState":{"cursorId":null,"cmd":{},"documents":[],"cursorIndex":0,"dead":false,"killed":false,"init":false,"notified":false,"limit":0,"skip":0,"batchSize":1000,"currentLimit":0,"reconnect":true}},"pool":null,"server":null,"ns":"HASTATE.$cmd","namespace":{"db":"HASTATE","collection":"$cmd"},"cmd":{},"options":{"readPreference":{"mode":"primary"}},"topology":{"_events":{"error":[null,null],"timeout":[null,null],"close":[null,null],"parseError":[null,null],"open":[null,null],"fullsetup":[null,null],"all":[null,null],"reconnect":[null,null]},"_eventsCount":35,"_maxListeners":null,"s":{"coreTopology":{"_events":{},"_eventsCount":20,"id":35,"s":{"options":{"metadata":{"driver":{"name":"nodejs","version":"3.6.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.118-0-virt"},"platform":"'Node.js v12.18.3, LE (legacy)"},"host":"192.168.66.211","port":27017,"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"reconnect":true,"emitError":true,"size":5,"monitorCommands":false,"checkServerIdentity":true,"rejectUnauthorized":true,"socketTimeout":360000,"connectionTimeout":10000,"servers":[{"host":"192.168.66.211","port":27017}],"caseTranslate":true,"directConnection":true,"sslValidate":true,"dbName":"HASTATE","socketTimeoutMS":360000,"connectTimeoutMS":10000,"retryWrites":true,"useRecoveryToken":true,"readPreference":{"mode":"primary"},"bson":{}},"logger":{"className":"Server"},"bson":{},"pool":{"_events":{},"_eventsCount":10,"topology":"[Circular ~.payload.topology.s.coreTopology]","s":{"state":"connected","cancellationToken":{"_events":{},"_eventsCount":0,"_maxListeners":null}},"options":{"host":"192.168.66.211","port":27017,"size":5,"minSize":0,"connectionTimeout":10000,"socketTimeout":360000,"keepAlive":true,"keepAliveInitialDelay":120000,"noDelay":true,"ssl":false,"checkServerIdentity":true,"ca":null,"crl":null,"cert":null,"key":null,"passphrase":null,"rejectUnauthorized":true,"promoteLongs":true,"promoteValues":true,"promoteBuffers":false,"reconnect":true,"reconnectInterval":1000,"reconnectTries":30,"domainsEnabled":false,"legacyCompatMode":true,"metadata":{"driver":{"name":"nodejs","version":"3.6.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.118-0-virt"},"platform":"'Node.js v12.18.3, LE (legacy)"},"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"emitError":true,"monitorCommands":false,"servers":[{"host":"192.168.66.211","port":27017}],"caseTranslate":true,"directConnection":true,"sslValidate":true,"dbName":"HASTATE","socketTimeoutMS":360000,"connectTimeoutMS":10000,"retryWrites":true,"useRecoveryToken":true,"readPreference":{"mode":"primary"},"bson":{}},"id":35,"retriesLeft":30,"reconnectId":null,"reconnectError":null,"logger":{"className":"Pool"},"availableConnections":[{"id":35,"host":"192.168.66.211","port":27017}],"inUseConnections":[],"connectingConnections":0,"executing":false,"queue":[],"numberOfConsecutiveTimeouts":0,"connectionIndex":1},"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"monitoring":true,"inTopology":false,"monitoringInterval":5000,"compression":{"compressors":[]},"clusterTime":null,"serverDescription":{"topologyType":"Single","servers":[{"address":"192.168.66.211:27017","arbiters":[],"hosts":[],"passives":[],"type":"Standalone"}]},"topologyDescription":{"topologyType":"Unknown","servers":[{"address":"192.168.66.211:27017","arbiters":[],"hosts":[],"passives":[],"type":"Unknown"}]}},"ismaster":{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":100000,"localTime":"2020-09-28T19:25:11.610Z","logicalSessionTimeoutMinutes":30,"minWireVersion":0,"maxWireVersion":7,"readOnly":false,"ok":1},"lastIsMasterMS":1,"monitoringProcessId":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev]","_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId]","_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2121888,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2120368,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2119778,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev._idlePrev._idlePrev]","_idleStart":2119502,"_repeat":null,"_destroyed":false},"expiry":2124502,"id":-9007199254738976,"msecs":5000,"priorityQueuePosition":1},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idlePrev]","_idleStart":2124451,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId]","_idleStart":2122271,"_repeat":null,"_destroyed":false},"_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext]","_idleNext":{"_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext]","_idleNext":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId]","_idleStart":2122271,"_repeat":null,"_destroyed":false},"_idleStart":2124451,"_repeat":null,"_destroyed":false},"_idlePrev":"[Circular ~.payload.topology.s.coreTopology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext]","expiry":2124502,"id":-9007199254738976,"msecs":5000,"priorityQueuePosition":1},"_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleStart":2119778,"_repeat":null,"_destroyed":false},"_idleStart":2120368,"_repeat":null,"_destroyed":false},"_idleStart":2121888,"_repeat":null,"_destroyed":false},"_idleStart":2121888,"_repeat":null,"_destroyed":false},"initialConnect":false,"_type":"server","lastUpdateTime":0,"lastWriteDate":0,"staleness":0},"sCapabilities":null,"clonedOptions":{"host":"192.168.66.211","port":27017,"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"reconnect":true,"emitError":true,"size":5,"monitorCommands":false,"checkServerIdentity":true,"rejectUnauthorized":true,"socketTimeout":360000,"connectionTimeout":10000},"reconnect":true,"emitError":true,"poolSize":5,"storeOptions":{"force":false,"bufferMaxEntries":-1},"store":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"host":"192.168.66.211","port":27017,"options":{"host":"192.168.66.211","port":27017,"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"reconnect":true,"emitError":true,"size":5,"monitorCommands":false,"checkServerIdentity":true,"rejectUnauthorized":true,"socketTimeout":360000,"connectionTimeout":10000,"servers":[{"host":"192.168.66.211","port":27017}],"caseTranslate":true,"directConnection":true,"sslValidate":true,"dbName":"HASTATE","socketTimeoutMS":360000,"connectTimeoutMS":10000,"retryWrites":true,"useRecoveryToken":true,"readPreference":{"mode":"primary"}},"sessionPool":{"topology":{"_events":{},"_eventsCount":20,"id":35,"s":{"options":{"metadata":{"driver":{"name":"nodejs","version":"3.6.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.118-0-virt"},"platform":"'Node.js v12.18.3, LE (legacy)"},"host":"192.168.66.211","port":27017,"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"reconnect":true,"emitError":true,"size":5,"monitorCommands":false,"checkServerIdentity":true,"rejectUnauthorized":true,"socketTimeout":360000,"connectionTimeout":10000,"servers":[{"host":"192.168.66.211","port":27017}],"caseTranslate":true,"directConnection":true,"sslValidate":true,"dbName":"HASTATE","socketTimeoutMS":360000,"connectTimeoutMS":10000,"retryWrites":true,"useRecoveryToken":true,"readPreference":{"mode":"primary"},"bson":{}},"logger":{"className":"Server"},"bson":{},"pool":{"_events":{},"_eventsCount":10,"topology":"[Circular ~.payload.topology.s.sessionPool.topology]","s":{"state":"connected","cancellationToken":{"_events":{},"_eventsCount":0,"_maxListeners":null}},"options":{"host":"192.168.66.211","port":27017,"size":5,"minSize":0,"connectionTimeout":10000,"socketTimeout":360000,"keepAlive":true,"keepAliveInitialDelay":120000,"noDelay":true,"ssl":false,"checkServerIdentity":true,"ca":null,"crl":null,"cert":null,"key":null,"passphrase":null,"rejectUnauthorized":true,"promoteLongs":true,"promoteValues":true,"promoteBuffers":false,"reconnect":true,"reconnectInterval":1000,"reconnectTries":30,"domainsEnabled":false,"legacyCompatMode":true,"metadata":{"driver":{"name":"nodejs","version":"3.6.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.118-0-virt"},"platform":"'Node.js v12.18.3, LE (legacy)"},"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"emitError":true,"monitorCommands":false,"servers":[{"host":"192.168.66.211","port":27017}],"caseTranslate":true,"directConnection":true,"sslValidate":true,"dbName":"HASTATE","socketTimeoutMS":360000,"connectTimeoutMS":10000,"retryWrites":true,"useRecoveryToken":true,"readPreference":{"mode":"primary"},"bson":{}},"id":35,"retriesLeft":30,"reconnectId":null,"reconnectError":null,"logger":{"className":"Pool"},"availableConnections":[{"id":35,"host":"192.168.66.211","port":27017}],"inUseConnections":[],"connectingConnections":0,"executing":false,"queue":[],"numberOfConsecutiveTimeouts":0,"connectionIndex":1},"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":"[Circular ~.payload.topology]"},"length":0},"monitoring":true,"inTopology":false,"monitoringInterval":5000,"compression":{"compressors":[]},"clusterTime":null,"serverDescription":{"topologyType":"Single","servers":[{"address":"192.168.66.211:27017","arbiters":[],"hosts":[],"passives":[],"type":"Standalone"}]},"topologyDescription":{"topologyType":"Unknown","servers":[{"address":"192.168.66.211:27017","arbiters":[],"hosts":[],"passives":[],"type":"Unknown"}]}},"ismaster":{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":100000,"localTime":"2020-09-28T19:25:11.610Z","logicalSessionTimeoutMinutes":30,"minWireVersion":0,"maxWireVersion":7,"readOnly":false,"ok":1},"lastIsMasterMS":1,"monitoringProcessId":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev]","_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId]","_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2121888,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2120368,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2119778,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev._idlePrev._idlePrev]","_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev._idlePrev._idlePrev]","_idleStart":2119502,"_repeat":null,"_destroyed":false},"expiry":2124502,"id":-9007199254738976,"msecs":5000,"priorityQueuePosition":1},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idlePrev]","_idleStart":2124451,"_repeat":null,"_destroyed":false},"_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId]","_idleStart":2122271,"_repeat":null,"_destroyed":false},"_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext]","_idleNext":{"_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext]","_idleNext":{"_idleTimeout":5000,"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext._idleNext]","_idleNext":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId]","_idleStart":2122271,"_repeat":null,"_destroyed":false},"_idleStart":2124451,"_repeat":null,"_destroyed":false},"_idlePrev":"[Circular ~.payload.topology.s.sessionPool.topology.monitoringProcessId._idleNext._idleNext._idleNext._idleNext._idleNext]","expiry":2124502,"id":-9007199254738976,"msecs":5000,"priorityQueuePosition":1},"_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleStart":2119502,"_repeat":null,"_destroyed":false},"_idleStart":2119778,"_repeat":null,"_destroyed":false},"_idleStart":2120368,"_repeat":null,"_destroyed":false},"_idleStart":2121888,"_repeat":null,"_destroyed":false},"_idleStart":2121888,"_repeat":null,"_destroyed":false},"initialConnect":false,"_type":"server","lastUpdateTime":0,"lastWriteDate":0,"staleness":0},"sessions":[]},"sessions":{}}},"cursorState":{"cursorId":null,"cmd":{},"documents":[],"cursorIndex":0,"dead":false,"killed":false,"init":false,"notified":false,"limit":0,"skip":0,"batchSize":1000,"currentLimit":0,"reconnect":true},"logger":{"className":"Cursor"},"s":{"numberOfRetries":5,"tailableRetryInterval":500,"currentNumberOfRetries":5,"state":0,"explicitlyIgnoreSession":false}}`

### What do you expect to happen?
The result I get with the query on mongo native or Robo-3T:
`/* 1 */
{
    "_id" : 1
}

/* 2 */
{
    "_id" : 0
}`

### Please tell us about your environment:

Runnning in docker, pulled today: nodered/node-red:latest-12 on X86_64 Bit alpine linux

`Linux docker-alpine 4.19.118-0-virt #1-Alpine SMP Thu Apr 23 11:54:03 UTC 2020 x86_64 Linux`

**Comment by FotoFieber** [comment]
Thx for the patch. I tried 0.2.2 and got following error:

`{"message":"ReferenceError: cursor is not defined","source":{"id":"3a5a5d64.130512","type":"mongodb in","name":"aggregate state","count":1},"stack":"ReferenceError: cursor is not defined\n    at /data/node_modules/node-red-node-mongodb/66-mongodb.js:282:38\n    at Collection.aggregate (/data/node_modules/mongodb/lib/collection.js:1894:5)\n    at MongoInNode._inputCallback (/data/node_modules/node-red-node-mongodb/66-mongodb.js:277:34)\n    at MongoInNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)\n    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)\n    at processImmediate (internal/timers.js:456:21)"}`
