### ISSUE TITLE
node-red-node-serialport: Upgrade from ?? to 0.13.0 fails in Node-RED

### ISSUE THREAD

**Issue by mark-veenstra** [node-red/node-red-nodes#772]
### Which node are you reporting an issue on?
node-red-node-serialport

### What are the steps to reproduce?
Have version 0.11.1 installed and hit the upgrade button in Node-RED to upgrade to 0.13.0

### What happens?
An error is thrown in de logfile with the following output and installation fails:
```
2021-03-17T14:22:05.015Z Install : node-red-node-serialport 0.13.0

2021-03-17T14:22:05.101Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-node-serialport@0.13.0
2021-03-17T14:22:22.879Z [out] 
2021-03-17T14:22:22.879Z [out] > @serialport/bindings@9.0.7 install /config/node-red/node_modules/@serialport/bindings
2021-03-17T14:22:22.879Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-03-17T14:22:22.879Z [out] 
2021-03-17T14:22:25.665Z [err] prebuild-install
2021-03-17T14:22:25.666Z [err]  WARN install No prebuilt binaries found (target=14.16.0 runtime=node arch=arm64 libc=musl platform=linux)
2021-03-17T14:22:30.254Z [err] gyp
2021-03-17T14:22:30.254Z [err]  
2021-03-17T14:22:30.254Z [err] ERR! build error 
2021-03-17T14:22:30.256Z [err] gyp 
2021-03-17T14:22:30.256Z [err] ERR! stack Error: not found: make
2021-03-17T14:22:30.256Z [err] gyp ERR! stack
2021-03-17T14:22:30.257Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-03-17T14:22:30.257Z [err] gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-03-17T14:22:30.257Z [err] gyp 
2021-03-17T14:22:30.257Z [err] ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-03-17T14:22:30.257Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-03-17T14:22:30.257Z [err] gyp ERR! stack
2021-03-17T14:22:30.257Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-03-17T14:22:30.257Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-03-17T14:22:30.257Z [err] gyp ERR! 
2021-03-17T14:22:30.258Z [err] stack     at FSReqCallback.oncomplete (fs.js:183:21)
2021-03-17T14:22:30.258Z [err] gyp ERR!
2021-03-17T14:22:30.258Z [err]  System Linux 5.4.83-v8
2021-03-17T14:22:30.258Z [err] gyp ERR! 
2021-03-17T14:22:30.259Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-03-17T14:22:30.259Z [err] gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-03-17T14:22:30.259Z [err] gyp
2021-03-17T14:22:30.259Z [err]  ERR! node -v v14.16.0
2021-03-17T14:22:30.259Z [err] gyp ERR! node-gyp -v
2021-03-17T14:22:30.259Z [err]  v5.1.0
2021-03-17T14:22:30.259Z [err] gyp ERR! not ok 
2021-03-17T14:22:31.195Z [err] npm 
2021-03-17T14:22:31.196Z [err] ERR! code ELIFECYCLE
2021-03-17T14:22:31.196Z [err] npm ERR! 
2021-03-17T14:22:31.196Z [err] errno 1
2021-03-17T14:22:31.215Z [err] npm ERR!
2021-03-17T14:22:31.215Z [err]  @serialport/bindings@9.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2021-03-17T14:22:31.215Z [err] npm ERR! Exit status 1
2021-03-17T14:22:31.215Z [err] npm ERR! 
2021-03-17T14:22:31.215Z [err] npm
2021-03-17T14:22:31.216Z [err]  ERR! Failed at the @serialport/bindings@9.0.7 install script.
2021-03-17T14:22:31.216Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-17T14:22:31.270Z [err] 
2021-03-17T14:22:31.271Z [err] npm ERR! A complete log of this run can be found in:
2021-03-17T14:22:31.271Z [err] npm ERR!     /root/.npm/_logs/2021-03-17T14_22_31_229Z-debug.log
2021-03-17T14:22:31.300Z rc=1
```

### What do you expect to happen?
That the upgrade would be successful and smoothly...

### Please tell us about your environment:

- [x] Node-RED version: `8.1.3`
- [x] node.js version: `node -v v14.16.0`
- [ ] npm version: 
- [x] Platform/OS: Raspbian - Home Assistant - https://www.home-assistant.io/installation/raspberrypi
- [x] Browser: Chrome

**Comment by hardillb** [comment]
This a is because the environment you are running Node-RED in doesn't have the basic build tools installed that are required to build the native components needed to open the serial port.

Given you mention you are running under Home Assistant you will need to discus this with them as to why the tools are missing and how to install them.

On normal raspbian you would run:

    $ sudo apt install build-essential

**Comment by dceejay** [comment]
Closing as not a Node-RED node issue
