### ISSUE TITLE
Deploy while email node is fetching crashes node red.

### ISSUE THREAD

**Issue by zachsteffens** [node-red/node-red-nodes#784]
### Which node are you reporting an issue on?
email node (input)
### What are the steps to reproduce?
set up email node
deploy - email node begins fetching (from gmail in my case)
make another change
deploy that change.
### What happens?
Nodered crashes and must be restarted via docker
stack trace below
`
 TypeError: Cannot read property 'fullcmd' of undefined
at Connection._resUntagged (/data/node_modules/node-red-node-email/node_modules/imap/lib/Connection.js:1408:45)
at Parser.<anonymous> (/data/node_modules/node-red-node-email/node_modules/imap/lib/Connection.js:191:10)
at Parser.emit (events.js:198:13)
at Parser._resUntagged (/data/node_modules/node-red-node-email/node_modules/imap/lib/Parser.js:271:10)
at Parser._parse (/data/node_modules/node-red-node-email/node_modules/imap/lib/Parser.js:137:16)
at Parser._tryread (/data/node_modules/node-red-node-email/node_modules/imap/lib/Parser.js:82:15)
at TLSSocket.Parser._cbReadable (/data/node_modules/node-red-node-email/node_modules/imap/lib/Parser.js:53:12)
at TLSSocket.emit (events.js:198:13)
at emitReadable_ (_stream_readable.js:555:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
`
### What do you expect to happen?
I expect it to deploy successfully.
### Please tell us about your environment:

- [1.2.8] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [Docker] Platform/OS:
- [FF,Chrome] Browser:

**Comment by dceejay** [comment]
fix in v1.10.1
