### ISSUE TITLE
Failed to install: node-red-node-sqlite

### ISSUE THREAD

**Issue by russo-g0** [node-red/node-red-nodes#801]
I tried to install node-red-node-sqlite 0.6.0, both from node-red’s manage palette, and from cmd by running this command npm i --unsafe-perm node-red-node-sqlite, but the installation is not successful, there are the following errors:

```
C:\Users\Utente\.node-red>npm i --unsafe-perm node-red-node-sqlite
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\Utente\.node-red\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "-m".
npm ERR!   unpack_sqlite_dep
npm ERR!   "python" non � riconosciuto come comando interno o esterno,
npm ERR!    un programma eseguibile o un file batch.
npm ERR! C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: la compilazione personalizzata per '..\..\deps\sqlite-autoconf-3310100.tar.gz' � stata terminata. Codice: 1. [C:\Users\Utente\.node-red\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Utente\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Utente\.node-red\node_modules\sqlite3\lib\binding\node-v88-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Utente\.node-red\node_modules\sqlite3\lib\binding\node-v88-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.6.0 | win32 | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "C:\Users\Utente\.node-red\node_modules\sqlite3\lib\binding\node-v88-win32-x64\node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-win32-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@15.6.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-win32-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.6.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.6.0 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
npm ERR! gyp info find VS using VS2019 (16.9.31205.134) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Utente\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Utente\\.node-red\\node_modules\\sqlite3\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Utente\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Utente\\AppData\\Local\\node-gyp\\Cache\\15.6.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Utente\\AppData\\Local\\node-gyp\\Cache\\15.6.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Utente\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Utente\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.6.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Utente\\.node-red\\node_modules\\sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Utente\\.node-red\\node_modules\\sqlite3\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.6.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Utente\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Utente\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Utente\\.node-red\\node_modules\\sqlite3\\lib\\binding\\node-v88-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Utente\\.node-red\\node_modules\\sqlite3\\lib\\binding\\node-v88-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd C:\Users\Utente\.node-red\node_modules\sqlite3
npm ERR! gyp ERR! node -v v15.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Utente\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Utente\.node-red\node_modules\sqlite3\lib\binding\node-v88-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Utente\.node-red\node_modules\sqlite3\lib\binding\node-v88-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Utente\.node-red\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1065:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Utente\\.node-red\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\Utente\.node-red\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v15.6.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utente\AppData\Local\npm-cache\_logs\2021-05-04T20_53_56_359Z-debug.log
```

- [ ] Node-RED version: 1.3.4
- [ ] node.js version: 15.6.0
- [ ] npm version: 7.11.1
- [ ] Platform/OS: Windows 10 Home  version 20H2
- [ ] Browser: Chrome

thanks in advance.

**Comment by hardillb** [comment]
The error says it failed to build the native component for the sqlite3 node (which the `node-red-node-sqlite` depends on)

If I had to guess this will because you are using NodeJS 15.x, but you need to raise it with the upstream node as it is something they will need to fix.

**Comment by Iam-rg0** [comment]
Okay, thanks.
so I try to install version 14 of node.js?

**Comment by hardillb** [comment]
If you change the NodeJS version it will be easier to totally remove Node-RED and reinstall it (otherwise you will have to use `npm rebuild` to rebuild ALL the npm nodes with native components.

You need to raise this with the sqlite3 node.

**Comment by knolleary** [comment]
Before you change node version (which I don't think is necessary here), you should deal with this error:
> "python" non � riconosciuto come comando interno o esterno,
> npm ERR!    un programma eseguibile o un file batch.

The sqlite node requires python to be installed.

**Comment by hardillb** [comment]
I saw that, but later on it has a valid path to python2.7

**Comment by Iam-rg0** [comment]
I have two versions of Python  on my pc: 
- I installed Python 2.7.18 from the site https://www.python.org/downloads/, and I installed Python 3.9.5 from Microsoft Store.

Do I need to delete both and install from the Python 3.9.5 CMD?

**Comment by hardillb** [comment]
If you already have python installed then there should be no need to reinstall it.

But as I said earlier, you need to raise this with the sqlite3 maintainers, while we can make suggestions, they are the best placed to actually solve the problem.

**Comment by Iam-rg0** [comment]
Okay, thanks for the support, I’ll ask them.
