### ISSUE TITLE
uninstall node-red-node-email not possable

### ISSUE THREAD

**Issue by krilor1** [node-red/node-red-nodes#822]
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment]
You need to fill out all the details in the template before we can help you

**Comment by krilor1** [comment]
running node red on ccu3
update to version 1.12.3. failed. now when starting node red i get error "nodes stopped due to missing nodes". neither install nor deinstall of node-red-node-email is possible. 
![node-red-node-email](https://user-images.githubusercontent.com/76907942/126907749-62608d88-0ab1-4d51-ac87-4e154297135e.png)

**Comment by hardillb** [comment]
There is no Node-RED version 7.2.1, the latest released version is 2.0.3
Also what is CCU?
We also need the NodeJS versions

**Comment by krilor1** [comment]
Unfortunately I don't know where to find all the information you need. In the attached picture you can see the configuration page which can be started from the ccu3 system. I hope this helps.

**Comment by knolleary** [comment]
Can you show us the log output when Node-RED starts? That will have the details of the error the email node is reporting.

**Comment by krilor1** [comment]
![image](https://user-images.githubusercontent.com/76907942/126909878-4f965c6e-981a-4589-96f6-2b2d7f51c530.jpeg)

**Comment by knolleary** [comment]
Without seeing the startup log of Node-RED there is not much we can do to help here.

You will have to check the redmatic docs for how to find the log - it isn't an environment we are familiar with.

https://github.com/rdmtc/RedMatic

**Comment by krilor1** [comment]
Jul 25 12:10:58 ccu3-webui daemon.err node-red[4809]: [google-tts:tts] Get key failed from google
Jul 25 12:10:58 ccu3-webui daemon.err node-red: (node:4809) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Jul 25 12:10:58 ccu3-webui daemon.err node-red: (Use `node --trace-deprecation ...` to show where the warning was created)
Jul 25 12:10:58 ccu3-webui daemon.err node-red: (node:4809) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
Jul 25 12:10:58 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-google-tts/google-tts.js:109:29
Jul 25 12:10:58 ccu3-webui daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Jul 25 12:10:58 ccu3-webui daemon.err node-red: (node:4809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jul 25 12:10:58 ccu3-webui daemon.err node-red: (node:4809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jul 25 13:56:54 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 13:56:58 ccu3-webui daemon.err node-red[4809]: [ccu-connection:localhost] xmlrpc server close timeout
Jul 25 13:57:00 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 13:57:05 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 13:57:05 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 14:00:07 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 14:00:09 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 14:00:13 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 14:00:13 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 14:07:03 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 14:07:05 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 14:07:09 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 14:07:09 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 14:16:19 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 14:16:21 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 14:16:25 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 14:16:25 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 18:31:07 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 18:31:09 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 18:31:14 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 18:31:14 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 18:45:03 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 18:45:05 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 18:45:10 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 18:45:10 ccu3-webui daemon.info redmatic: Starting Node-RED
Jul 25 18:57:59 ccu3-webui daemon.info redmatic: Stopping Node-RED
Jul 25 18:58:01 ccu3-webui daemon.info redmatic: Node-RED stopped
Jul 25 18:58:05 ccu3-webui daemon.info redmatic: RedMatic v7.2.1 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Jul 25 18:58:05 ccu3-webui daemon.info redmatic: Starting Node-RED

**Comment by knolleary** [comment]
Ok - so that is some of the log. What we really need is the log output from Node-RED itself. It looks like this:
```

25 Jul 19:49:39 - [info]

Welcome to Node-RED
===================

25 Jul 19:49:39 - [info] Node-RED version: v2.0.3
25 Jul 19:49:39 - [info] Node.js  version: v14.17.0
25 Jul 19:49:39 - [info] Darwin 20.5.0 x64 LE
25 Jul 19:49:39 - [info] Loading palette nodes
25 Jul 19:49:40 - [info] Dashboard version 2.29.3 started at /ui
25 Jul 19:49:40 - [warn] ------------------------------------------------------
25 Jul 19:49:40 - [warn] [node-red-node-rbe/rbe] 'rbe' already registered by module node-red
25 Jul 19:49:40 - [warn] ------------------------------------------------------
25 Jul 19:49:40 - [info] Settings file  : /Users/nol/.node-red/settings.js
25 Jul 19:49:40 - [info] Context store  : 'default' [module=memory]
25 Jul 19:49:40 - [info] User directory : /Users/nol/.node-re
```

**Comment by krilor1** [comment]
Attached you can find the complete log file.

**Comment by krilor1** [comment]
Did you get my email?

**Comment by hardillb** [comment]
Email attachments do not get added to the issue so there is nothing linked to that last update. You have to add them via the web.

**Comment by krilor1** [comment]
[redmatic.2021-07-25T18_44_45.087Z.log](https://github.com/node-red/node-red-nodes/files/6874430/redmatic.2021-07-25T18_44_45.087Z.log)

**Comment by hardillb** [comment]
OK, so it looks like the RedMatic developer has removed all the useful information from the startup log.

Looking at their github page for the release (https://github.com/rdmtc/RedMatic/releases/tag/v7.2.1)

It looks like:
NodeJS: 14.16.0
NPM: 7.6.3
Node-RED: 1.2.9

The Original email node was 1.8.3

**Comment by krilor1** [comment]
So can you help?

**Comment by hardillb** [comment]
Not easily, without seeing why Node-RED failed to load the email node we can't see what we need to fix.

I think you need to talk to the RedMatic folk to work out how to get all the log output from Node-RED.

**Comment by krilor1** [comment]
Is there any alternative option to uninstall the node by the palette? Then I simply could install it again.

**Comment by hardillb** [comment]
If you can get a shell on the device you can run `npm uninstall node-red-node-email` in the userDir for the Node-RED instance.

Without the logs I can't tell you where the userDir is.

**Comment by Steve-Mcl** [comment]
closing as upstream issue.
