### ISSUE TITLE
node-red-node-sqlite installation failure

### ISSUE THREAD

**Issue by ThirtySomething** [node-red/node-red-nodes#874]
### Which node are you reporting an issue on?
node-red-node-sqlite

### What are the steps to reproduce?
npm i node-red-node-sqlite

### What happens?
Installation is aborted with unclear error message.

```
15791 warn node-red-project@0.0.1 No repository field.
15792 warn node-red-project@0.0.1 No license field.
15793 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
15794 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
15795 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
15795 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
15795 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
15795 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
15796 verbose stack Error: sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
15796 verbose stack Exit status 1
15796 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
15796 verbose stack     at EventEmitter.emit (events.js:400:28)
15796 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
15796 verbose stack     at ChildProcess.emit (events.js:400:28)
15796 verbose stack     at maybeClose (internal/child_process.js:1058:16)
15796 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
15797 verbose pkgid sqlite3@4.1.1
15798 verbose cwd /home/pi/.node-red
15799 verbose Linux 5.10.63-v8+
15800 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
15801 verbose node v14.18.3
15802 verbose npm  v6.14.15
15803 error code ELIFECYCLE
15804 error errno 1
15805 error sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
15805 error Exit status 1
15806 error Failed at the sqlite3@4.1.1 install script.
15806 error This is probably not a problem with npm. There is likely additional logging output above.
15807 verbose exit [ 1, true ]
```

### What do you expect to happen?
* The node should be installed, but does not.
* Clear error message like "Some script requires Python 2".

### Please tell us about your environment:
- [ ] Node-RED version: 2.1.4
- [ ] node.js version: 14.18.3
- [ ] npm version: 6.14.15
- [ ] Platform/OS:  Raspberry Pi 3+, [Raspbian 64 bit](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/) with Kernel 5.10.63
- [ ] Browser: Google Chrome

SQLite3 is already installed with `sudo apt-get install sqlite3` - the version is 3.34.1-3. The CLI and also a GUI based db-browser are working as expected. Somewhere in the errorlog I've found a hint about SQLite3 version 4.1.1.  - I wonder because the latest official release is version [3.37.2](https://www.sqlite.org/index.html).

Somewhere [here](https://github.com/mapbox/node-pre-gyp/issues/477) there was the final hint to solve the problem. On the OS there is no Python 2 but Python 3 installed. So I've installed additional Python 2 and set the autoselect as described [here](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux). Now the node installs and is working as expected. But... it this was really hard to find.

**Comment by hardillb** [comment]
I think the problem here is we are waiting on the node-sqlite3 project to merge this PR https://github.com/mapbox/node-sqlite3/pull/1522 which will update the version of node-gyp used to build the native wrapper.

Version 8 of node-gyp uses Python 3, Python 2 is end of life and shouldn't really be being used at all any more.

**Comment by ThirtySomething** [comment]
@hardillb thanks for your reply. Then I'm trying to be patient.
